In [2]:
import os
import qsprpred

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.descriptors.sets import RDKitDescs

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [3]:
def load_datasets(path):
    dataset = QSPRDataset.fromTableFile(
    filename=path,
    store_dir="dataset_outputs/A2AR/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    feature_calculators=[MorganFP(radius=2, nBits=1024)],
    recalculate_features=True,
    shuffle=False
    )
    from qsprpred.data.descriptors.sets import RDKitDescs
    
    rdkit_descs = RDKitDescs()
    
    dataset.addDescriptors([rdkit_descs])
    
    dataset.descriptorSets
    return dataset

In [4]:
import torch
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizerFast, RobertaForMaskedLM, DataCollatorWithPadding
from sklearn.base import BaseEstimator, TransformerMixin

class SMILESDataset(Dataset):
    def __init__(self, smiles, tokenizer, max_len=128):
        self.smiles = smiles
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.smiles)

    def __getitem__(self, idx):
        smile = self.smiles[idx]
        encoding = self.tokenizer(smile, truncation=True, padding='max_length', max_length=self.max_len, return_tensors='pt')
        return encoding


class ChemBERTaTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, model_name="entropy/roberta_zinc_480m", max_len=128, batch_size=32, device=None):
        self.model_name = model_name
        self.max_len = max_len
        self.batch_size = batch_size
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.model = RobertaForMaskedLM.from_pretrained(self.model_name).to(self.device)
        self.tokenizer = RobertaTokenizerFast.from_pretrained(self.model_name, max_len=self.max_len)
        self.collator = DataCollatorWithPadding(self.tokenizer, padding=True, return_tensors='pt')
        self.embedding_dim = None  # bude nastaven po fit()

    def fit(self, X, y=None):
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=1, collate_fn=self.collator)
        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                embedding = outputs[1][-1]  # poslední hidden state
                self.embedding_dim = embedding.shape[-1]
                break
        return self

    def transform(self, X):
        self.model.eval()
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=self.batch_size, collate_fn=self.collator)
        embeddings_list = []

        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                full_embeddings = outputs[1][-1]
                embeddings = ((full_embeddings * attention_mask.unsqueeze(-1)).sum(1) / attention_mask.sum(-1).unsqueeze(-1))
                embeddings_list.append(embeddings)

        all_embeddings = torch.cat(embeddings_list, dim=0).cpu().numpy()
        column_names = [f"chemberta_{i}" for i in range(self.embedding_dim)]
        return pd.DataFrame(all_embeddings, columns=column_names)

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X1_all = load_datasets("A2AR/data/a2ar_train_1")

X2_all = load_datasets("A2AR/data/a2ar_val_1")

X3_all = load_datasets("A2AR/data/a2ar_test")

transformer = ChemBERTaTransformer()
X_train_emb = transformer.fit_transform(X1_all.df["Drug"])
X_val_emb = transformer.transform(X2_all.df["Drug"])
X_test_emb = transformer.transform(X3_all.df["Drug"])

/tmp/ipykernel_25954/4135545419.py:17: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  smile = self.smiles[idx]

In [6]:
import pandas as pd
X1_all.X = X1_all.X.reset_index(drop=True)
X_train_emb = X_train_emb.reset_index(drop=True)
X1_all.X = pd.concat([X1_all.X, X_train_emb], axis = 1)

In [7]:
X2_all.X = X2_all.X.reset_index(drop=True)
X_val_emb = X_val_emb.reset_index(drop=True)
X2_all.X = pd.concat([X2_all.X, X_val_emb], axis = 1)
X3_all.X = X3_all.X.reset_index(drop=True)
X_test_emb = X_test_emb.reset_index(drop=True)
X3_all.X = pd.concat([X3_all.X, X_test_emb], axis = 1)

In [8]:
X1 = X1_all.X
y1 = X1_all.y
X2 = X2_all.X
y2 = X2_all.y
X3 = X3_all.X
y3 = X3_all.y

In [9]:
imp_mean = SimpleImputer(missing_values=pd.NA, strategy='mean')
X1 = imp_mean.fit_transform(X1)
X2 = imp_mean.transform(X2)
X3 = imp_mean.transform(X3)
scaler = StandardScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)
X2 = scaler.transform(X2)
X3 = scaler.transform(X3)

In [10]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy=0.5, random_state=42)
X1, y1 = smote.fit_resample(X1, y1)
display(pd.DataFrame(X1))

,0,1,2,3,4,5,6,7,8,9,...,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001
0,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,-0.287995,0.475829,-1.886007,-0.019086,1.685174,-1.575181,-1.036012,0.372024,0.183762,-1.731507
1,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,-0.847985,-0.123727,1.436241,0.550994,-0.118027,0.899331,1.255971,0.138340,0.360206,-1.591655
2,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,1.489012,-0.145865,-0.276977,...,0.016308,-0.615823,-0.601442,-1.669977,1.384967,0.730146,1.281295,-1.245225,-1.563946,1.619037
3,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,0.648537,-1.275505,0.558520,0.940265,-0.989957,0.098584,-0.791973,0.670594,-0.313377,0.854122
4,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,-1.294618,0.290985,0.112522,1.052698,-0.938391,-0.994478,-0.979179,1.762197,-0.801921,-0.096545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3460,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,1.489012,-0.145865,-0.276977,...,1.221856,0.039337,-0.345848,-0.257785,-0.808051,-1.189340,-0.115003,1.100244,1.236962,0.473864
3461,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,0.481551,1.128323,-1.079669,-0.538365,-0.174570,0.675272,0.816715,-0.223604,0.418711,-1.436246
3462,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,1.203936,-0.145865,-0.276977,...,1.169177,-0.821740,-0.880680,0.016980,-1.051404,-0.861372,1.060975,0.735636,2.086703,-0.020123
3463,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,1.154101,-1.817191,-1.057004,2.039169,-0.542305,-0.117311,2.184166,-0.026589,-1.009716,1.977249
3464,-0.098367,-0.323209,-0.110594,-0.119876,-0.098367,-0.057831,-0.073798,-0.671586,-0.145865,-0.276977,...,1.086061,0.814530,-0.390981,-1.390821,-0.902463,-1.256858,0.638193,-0.948310,0.659704,0.311912

In [27]:

# Přidejte cestu k vašemu lokálnímu repozitáři
import sys
import os

# Přidání cesty k lokálnímu repozitáři na začátek sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Zkontrolujte, zda je cesta v sys.path
print(sys.path)

from importlib import reload

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected
# Znovu načtěte modul, abyste zajistili, že je správně importován
reload(sys.modules['qsprpred.extra.gpu.models.neural_network'])

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected

os.chdir('/home/ubuntu/Bakalarka/QSPRpred')
print(os.getcwd())


import sys
import importlib.util

# Přidání cesty k repozitáři do sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Specifikujte cestu k souboru, který chcete importovat
module_path = '/home/ubuntu/Bakalarka/QSPRpred/qsprpred/extra/gpu/models/neural_network.py'
module_name = 'qsprpred.extra.gpu.models.neural_network'

# Načtěte modul z konkrétní cesty
spec = importlib.util.spec_from_file_location(module_name, module_path)
neural_network = importlib.util.module_from_spec(spec)
spec.loader.exec_module(neural_network)

# Nyní můžete používat třídu STFullyConnected
STFullyConnected = neural_network.STFullyConnected

['/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python311.zip', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/lib-dynload', '', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages']
/home/ubuntu/Bakalarka/QSPRpred
lol

In [12]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, matthews_corrcoef
import pandas as pd

def test_fun(dic,  X_train, y_train, X_test, y_test) -> pd.DataFrame:
    param_grid_t = ParameterGrid(dic)
    i = 0
    val_f1_t = []
    val_acc_t = []
    val_mcc_t = []
    param_len_t = len(param_grid_t)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Device used:", device)
    for param in param_grid_t:
        i += 1
        print(i, '/', param_len_t)
        model_sts_t = STFullyConnected(n_dim=X_train.shape[1],  # počet vstupních neuronů (počet deskriptorů)
        n_class=1,  # regresní úloha (1 výstup)
        gpus=[],
        device=device,
        is_reg=False, **param)
        model_sts_t.fit(X_train, y_train)
        res = model_sts_t.predict(X_test)
        res = res >0.5
        val_f1_t.append(f1_score(res, y_test))
        val_acc_t.append(accuracy_score(res, y_test))
        val_mcc_t.append(matthews_corrcoef(res, y_test))
        print(param)
        print(f1_score(res, y_test))
        print(accuracy_score(res, y_test))
        print(matthews_corrcoef(res, y_test))
    my_df = pd.DataFrame(param_grid_t)
    my_df["F1"] = val_f1_t
    my_df["Acc"] = val_acc_t
    my_df["MCC"] = val_mcc_t
    my_df.sort_values(by="MCC", ascending=False, inplace=True)
    return my_df

In [18]:
from torch import optim
import torch
my_dict_ult = {
    "act_fun": [F.selu],
    "dropout_frac": [0, 0.15, 0.3, 0.45, 0.7, 0.9],
    "patience": [75],
    "tol": [1e-5],
    "weight_decay": [1e-4,],
    "n_epochs": [300],
    "neuron_layers": [[ 5000, 2500], [8192,4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256, 128]]
    , "batch_size": [256]
    , "optimizer": [optim.AdamW] ,
    "lr": [ 1e-2, 1e-3, 1e-4]
}
df_batch_ult = test_fun(my_dict_ult, X1, y1, X2, y2)
df_batch_ult
#starej

Device used: cuda
1 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
2 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
3 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8876636802205375
0.7985166872682324
-0.05372467063553557
4 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
5 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9669475048606611
0.9369592088998764
0.29486286054905725
6 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9764181007010835
0.9542645241038319
0.22873349178001748
7 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9762057877813505
0.9542645241038319
0.3894385848938405
8 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9761751448808758
0.9542645241038319
0.4084042349728781
9 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9606299212598425
0.9258343634116193
0.3544846099854445
10 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9538258575197889
0.9134734239802225
0.30623197187066065
11 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9653821032005225
0.934487021013597
0.3805037857207209
12 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9606299212598425
0.9258343634116193
0.3544846099854445
13 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
14 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
15 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8636042402826856
0.761433868974042
-0.022580030337685537
16 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
17 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9704370179948586
0.9431396786155748
0.22866218764908505
18 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9794871794871794
0.9604449938195303
0.42806217344453845
19 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9742268041237113
0.9505562422744128
0.37005272064416217
20 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9716859716859717
0.9456118665018541
0.28490478796071117
21 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9592641261498029
0.92336217552534
0.3477694377228392
22 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9593175853018373
0.92336217552534
0.3302491625521457
23 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9660574412532638
0.9357231149567367
0.3845867723434868
24 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9503639973527466
0.907292954264524
0.29299917443129647
25 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
26 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
27 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
28 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
29 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9748873148744366
0.9517923362175525
0.3762517411919265
30 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9795134443021767
0.9604449938195303
0.40931463246325
31 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9715394566623544
0.9456118665018541
0.36686412310418554
32 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9762363519588954
0.9542645241038319
0.3697392661436588
33 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9585798816568047
0.9221260815822002
0.34451675717963304
34 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.962671905697446
0.9295426452410384
0.3651240763225549
35 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9544554455445544
0.9147095179233622
0.3263178509930108
36 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9531353135313532
0.9122373300370828
0.30348717197775993
37 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
38 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
39 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
40 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
41 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9775208734746307
0.9567367119901112
0.4038152591158871
42 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9808917197452229
0.9629171817058096
0.3695476770183363
43 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9741602067183462
0.9505562422744128
0.4078460547922969
44 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9801409352978859
0.9616810877626699
0.43698890932436624
45 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9592641261498029
0.92336217552534
0.3477694377228392
46 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.954515491100857
0.9147095179233622
0.3090292968874092
47 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9565217391304348
0.9184177997527813
0.33514840049581723
48 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.951058201058201
0.9085290482076638
0.2955507030307519
49 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
50 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
51 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
52 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
53 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9787781350482315
0.9592088998763906
0.4555781493273698
54 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9756722151088348
0.9530284301606922
0.29804597061420124
55 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.982769623484365
0.9666254635352287
0.46162366649134795
56 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9782608695652174
0.957972805933251
0.3512349161335701
57 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9585798816568047
0.9221260815822002
0.34451675717963304
58 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9681197137280416
0.9394313967861557
0.37974216418761136
59 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9654272667971298
0.934487021013597
0.36278674374325176
60 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9674054758800521
0.9381953028430161
0.3930687210718959
61 / 72
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
62 / 72

,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
54,<function selu at 0x7f97a88ab560>,256,0.70,0.001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.982770,0.966625,0.461624
52,<function selu at 0x7f97a88ab560>,256,0.70,0.001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.978778,0.959209,0.455578
43,<function selu at 0x7f97a88ab560>,256,0.45,0.001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.980141,0.961681,0.436989
17,<function selu at 0x7f97a88ab560>,256,0.15,0.001,300,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.979487,0.960445,0.428062
66,<function selu at 0x7f97a88ab560>,256,0.90,0.001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.977492,0.956737,0.422508
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,<function selu at 0x7f97a88ab560>,256,0.70,0.010,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
49,<function selu at 0x7f97a88ab560>,256,0.70,0.010,300,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
36,<function selu at 0x7f97a88ab560>,256,0.45,0.010,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
14,<function selu at 0x7f97a88ab560>,256,0.15,0.010,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.863604,0.761434,-0.022580
2,<function selu at 0x7f97a88ab560>,256,0.00,0.010,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.887664,0.798517,-0.053725

In [14]:
df_batch_ult.to_csv()

,Unnamed: 0,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
100,100,<function selu at 0x7f64b0cb4ea0>,256,0.70,0.00100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.982770,0.966625,0.461624
101,101,<function selu at 0x7f64b0cb4ea0>,256,0.70,0.00100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00000,0.0001,0.982770,0.966625,0.461624
97,97,<function selu at 0x7f64b0cb4ea0>,256,0.70,0.00100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00000,0.0001,0.978778,0.959209,0.455578
96,96,<function selu at 0x7f64b0cb4ea0>,256,0.70,0.00100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.978778,0.959209,0.455578
46,46,<function selu at 0x7f64b0cb4ea0>,256,0.15,0.00001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974757,0.951792,0.449205
47,47,<function selu at 0x7f64b0cb4ea0>,256,0.15,0.00001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00000,0.0001,0.974757,0.951792,0.449205
45,45,<function selu at 0x7f64b0cb4ea0>,256,0.15,0.00001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00000,0.0001,0.975452,0.953028,0.438020
44,44,<function selu at 0x7f64b0cb4ea0>,256,0.15,0.00001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.975452,0.953028,0.438020
78,78,<function selu at 0x7f64b0cb4ea0>,256,0.45,0.00100,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.980141,0.961681,0.436989
79,79,<function selu at 0x7f64b0cb4ea0>,256,0.45,0.00100,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00000,0.0001,0.980141,0.961681,0.436989

In [ ]:
df = pd.read_csv("dataset_outputs/A2AR/tabs/A2ARbatch6.csv")

In [ ]:
from pathlib import Path

cesta = Path('qsprpred/extra/gpu/models/dataset_outputs/A2AR/tabs/')
pocet_souboru = sum(1 for f in cesta.iterdir() if f.is_file())
my_df.to_csv(f'qsprpred/extra/gpu/models/dataset_outputs/A2AR/tabs/A2ARbatch{}.csv')

In [ ]:
from torch import optim
import torch
my_dict_ult = {
    "act_fun": [F.selu],
    "dropout_frac": [0.6, 0.7, 0.8, 0.9],
    "patience": [75],
    "tol": [1e-5],
    "weight_decay": [1e-4],
    "n_epochs": [300],
    "neuron_layers": [[4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256, 128],
                     [4096, 2048, 1024, 1024, 512, 256], [4096, 2048, 1024, 512], [2048, 1024, 512, 256, 128]]
    , "batch_size": [256]
    , "optimizer": [optim.AdamW,] ,
    "lr": [1e-3, 1e-2]
}
df_batch_ult = test_fun(my_dict_ult, X1, y1, X2, y2)
df_batch_ult

Device used: cuda
1 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9445557782231129
0.8974042027194067
0.32349618013058984
2 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9636363636363636
0.930778739184178
0.2552926455610421
3 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.974293059125964
0.9505562422744128
0.3293449034372435
4 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9749839640795381
0.9517923362175525
0.3140230598635097
5 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9668615984405458
0.9369592088998764
0.3340923277925644
6 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9445557782231129
0.8974042027194067
0.32349618013058984
7 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9636363636363636
0.930778739184178
0.2552926455610421
8 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.974293059125964
0.9505562422744128
0.3293449034372435
9 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9749839640795381
0.9517923362175525
0.3140230598635097
10 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.6, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9668615984405458
0.9369592088998764
0.3340923277925644
11 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9729032258064516
0.9480840543881335
0.358356736165542
12 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9769820971867008
0.9555006180469716
0.3126800929107671
13 / 40
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9676165803108808
0.9381953028430161
0.29906942090006716
14 / 40

In [1]:
len(X1)

NameError: name 'X1' is not defined

In [20]:
from torch import optim
import torch
my_dict_ult = {
    "act_fun": [F.selu],
    "dropout_frac": [0, 0.15, 0.3, 0.45, 0.7, 0.9],
    "patience": [75],
    "tol": [1e-5],
    "weight_decay": [1e-4,],
    "n_epochs": [300],
    "neuron_layers": [[ 5000, 2500], [8192,4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256, 128]]
    , "batch_size": [256]
    , "optimizer": [optim.AdamW] ,
    "lr": [1e-1, 1e-2, 1e-3, 1e-4]
}
df_batch_ult = test_fun(my_dict_ult, X1, y1, X2, y2)
df_batch_ult
#s

Device used: cuda
1 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
2 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
3 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
4 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
5 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
6 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
7 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9517601043024772
0.9085290482076638
0.07856190955240645
8 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
9 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9018789144050104
0.8257107540173053
0.24176595743023802
10 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8981288981288982
0.8182941903584673
0.1470649145461265
11 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.867816091954023
0.7725587144622992
0.20964636545467308
12 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8720514653323803
0.7787391841779975
0.20083833531860792
13 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9604221635883905
0.9258343634116193
0.421097358203823
14 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9500998003992016
0.907292954264524
0.35940801151738505
15 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9542743538767395
0.9147095179233622
0.37617449504910744
16 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9465954606141522
0.9011124845488258
0.3466369351005504
17 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
18 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
19 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
20 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
21 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
22 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
23 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9158249158249159
0.8454882571075402
0.0035416246907995015
24 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
25 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9109730848861284
0.8405438813349815
0.2574357456558017
26 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8421052631578947
0.7330037082818294
0.1299839951079451
27 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8076045627376426
0.6872682323856613
0.2058036249735795
28 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8472834067547724
0.7428924598269468
0.22771506541649075
29 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9591029023746702
0.92336217552534
0.3981242809371905
30 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9494007989347537
0.9060568603213844
0.35677234087565524
31 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9487008660892738
0.9048207663782447
0.3541785587702203
32 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9416498993963782
0.892459826946848
0.33030542198093754
33 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
34 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
35 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
36 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
37 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.783011583011583
0.6526576019777504
0.13793448865662883
38 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
39 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9713558243157224
0.9443757725587144
0.016856010015318383
40 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
41 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9435965494359655
0.8949320148331273
0.21784614938572588
42 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8768683274021353
0.7861557478368356
0.2066025309850166
43 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9133425034387895
0.8442521631644005
0.2468882844305618
44 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.950863213811421
0.9085290482076638
0.34590464444722024
45 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9577278731836195
0.9208899876390606
0.3915583887066298
46 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.946524064171123
0.9011124845488258
0.36240278931953807
47 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9444072337575352
0.8974042027194067
0.35512269654708284
48 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9307065217391305
0.8739184177997528
0.33033712900465584
49 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
50 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
51 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
52 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
53 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9513933895009722
0.907292954264524
-0.04762680805709826
54 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
55 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
56 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
57 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9552631578947368
0.9159456118665018
0.2941801782246912
58 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8980446927374302
0.8195302843016069
0.23569457928334808
59 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9345037137069547
0.8800988875154512
0.30956380416908513
60 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9387205387205387
0.8875154511742892
0.3371578190234402
61 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9556585043017869
0.9171817058096415
0.38216085662611265
62 / 96
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9365721997300944
0.8838071693448702
0.3309041990854679
63 / 96

,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
12,<function selu at 0x7f97a88ab560>,256,0.00,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.960422,0.925834,0.421097
28,<function selu at 0x7f97a88ab560>,256,0.15,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.959103,0.923362,0.398124
44,<function selu at 0x7f97a88ab560>,256,0.30,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.957728,0.920890,0.391558
60,<function selu at 0x7f97a88ab560>,256,0.45,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.955659,0.917182,0.382161
14,<function selu at 0x7f97a88ab560>,256,0.00,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.954274,0.914710,0.376174
...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,<function selu at 0x7f97a88ab560>,256,0.45,0.0100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
84,<function selu at 0x7f97a88ab560>,256,0.90,0.0100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.980466,0.961681,-0.006904
89,<function selu at 0x7f97a88ab560>,256,0.90,0.0010,300,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.499051,0.347342,-0.024888
52,<function selu at 0x7f97a88ab560>,256,0.45,0.0100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.951393,0.907293,-0.047627
95,<function selu at 0x7f97a88ab560>,256,0.90,0.0001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.779043,0.640297,-0.069982

In [26]:
from torch import optim
import torch
my_dict_ult = {
    "act_fun": [F.selu],
    "dropout_frac": [0, 0.15, 0.3, 0.45, 0.7, 0.9],
    "patience": [75],
    "tol": [1e-5],
    "weight_decay": [1e-4,],
    "n_epochs": [300],
    "neuron_layers": [[ 5000, 2500], [8192,4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256, 128]]
    , "batch_size": [256]
    , "optimizer": [optim.AdamW] ,
    "lr": [1e-1, 1e-2, 1e-3, 1e-4]
}
df_batch_ult_plat = test_fun(my_dict_ult, X1, y1, X2, y2)
df_batch_ult_plat
#plat

Device used: cuda
1 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
2 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
3 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
4 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
5 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
6 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
7 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8876636802205375
0.7985166872682324
-0.05372467063553557
8 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
9 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9675745784695201
0.9381953028430161
0.31903114598250704
10 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
11 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.979565772669221
0.9604449938195303
0.3693692613899826
12 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9768934531450578
0.9555006180469716
0.3768934531450578
13 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9453333333333334
0.8986402966625463
0.3096070154292293
14 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9621903520208605
0.9283065512978986
0.28823311723206607
15 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.961463096015676
0.927070457354759
0.30382167263061133
16 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9426666666666667
0.8936959208899876
0.26758854948689637
17 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
18 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
19 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
20 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
21 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
22 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
23 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
24 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
25 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
26 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
27 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9775497113534317
0.9567367119901112
0.38439554059192504
28 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9821428571428571
0.965389369592089
0.4321583502625548
29 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9432955303535691
0.8949320148331273
0.2863958532540799
30 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9627207325049052
0.9295426452410384
0.3474742876929361
31 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9579500657030223
0.9208899876390606
0.3238719200877609
32 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9581151832460733
0.9208899876390606
0.2689807224710823
33 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
34 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
35 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
36 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
37 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
38 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
39 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.17462165308498254
0.12360939431396786
-0.04455821538344619
40 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
41 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
42 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
43 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9781491002570694
0.957972805933251
0.43002761922540195
44 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8776671408250356
0.7873918417799752
0.2075849982645099
45 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9475083056478405
0.9023485784919654
0.30013550318158716
46 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9682024659312135
0.9394313967861557
0.34275259162137706
47 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9539473684210527
0.9134734239802225
0.27060496631941383
48 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.3, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9564643799472295
0.9184177997527813
0.3521781264039256
49 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
50 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
51 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
52 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
53 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
54 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
55 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
56 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
57 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9724535554131967
0.9468479604449939
0.21847194570424947
58 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
59 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9592105263157895
0.92336217552534
0.36490581394052335
60 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9768637532133676
0.9555006180469716
0.39646671396268246
61 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9439252336448598
0.896168108776267
0.30503021692601845
62 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.964122635355512
0.9320148331273177
0.33679998301292674
63 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9625738673670388
0.9295426452410384
0.3992200769961277
64 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.45, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9560078791858174
0.9171817058096415
0.27889780507530687
65 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
66 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
67 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
68 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
69 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
70 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
71 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
72 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
73 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9605781865965834
0.9258343634116193
0.3716669553579175
74 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
75 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8736616702355461
0.7812113720642769
0.20273542204641423
76 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8684399712437095
0.7737948084054388
0.22396008108862417
77 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9516876240900066
0.9097651421508035
0.31528959498000053
78 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9661898569570871
0.9357231149567367
0.3299449711723647
79 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9468791500664011
0.9011124845488258
0.28088175140458965
80 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.7, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9484126984126984
0.9035846724351051
0.2507081451252984
81 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
82 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
83 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
84 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
85 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
86 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
87 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
88 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9594333547971667
0.9221260815822002
-0.009578184179492372
89 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9467376830892144
0.9011124845488258
0.31432692561559566
90 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
91 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.973565441650548
0.9493201483312732
0.36409295497774213
92 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
93 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9593175853018373
0.92336217552534
0.3302491625521457
94 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9487008660892738
0.9048207663782447
0.3541785587702203
95 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9448504983388705
0.8974042027194067
0.25701917146287917
96 / 96

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/torch/optim/lr_scheduler.py:28: UserWarning: The verbose parameter is deprecated. Please use get_last_lr() to access the learning rate.
  warnings.warn("The verbose parameter is deprecated. Please use get_last_lr() "

{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.9, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9600523903077931
0.9245982694684796
0.3155752416760822

,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
27,<function selu at 0x7f97a88ab560>,256,0.15,0.0010,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.982143,0.965389,0.432158
42,<function selu at 0x7f97a88ab560>,256,0.30,0.0010,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.978149,0.957973,0.430028
62,<function selu at 0x7f97a88ab560>,256,0.45,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.962574,0.929543,0.399220
59,<function selu at 0x7f97a88ab560>,256,0.45,0.0010,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.976864,0.955501,0.396467
26,<function selu at 0x7f97a88ab560>,256,0.15,0.0010,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.977550,0.956737,0.384396
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35,<function selu at 0x7f97a88ab560>,256,0.30,0.1000,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.000000,0.037083,0.000000
48,<function selu at 0x7f97a88ab560>,256,0.45,0.1000,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.000000,0.037083,0.000000
87,<function selu at 0x7f97a88ab560>,256,0.90,0.0100,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.959433,0.922126,-0.009578
38,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.174622,0.123609,-0.044558
6,<function selu at 0x7f97a88ab560>,256,0.00,0.0100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.887664,0.798517,-0.053725

In [28]:
from torch import optim
import torch
my_dict_ult = {
    "act_fun": [F.selu],
    "dropout_frac": [0, 0.15, 0.3, 0.45, 0.7, 0.9],
    "patience": [75],
    "tol": [1e-5],
    "weight_decay": [1e-4,],
    "n_epochs": [300, 500],
    "neuron_layers": [[ 5000, 2500], [8192,4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256], [4096, 2048, 1024, 512, 256, 128]]
    , "batch_size": [256]
    , "optimizer": [optim.AdamW] ,
    "lr": [1e-1, 1e-2, 1e-3, 1e-4]
}
df_batch_ult_onecycle = test_fun(my_dict_ult, X1, y1, X2, y2)
df_batch_ult_onecycle
#s

Device used: cuda
1 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
2 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
3 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
4 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
5 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
6 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
7 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
8 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
9 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8642501776830135
0.7639060568603214
0.05160991824795554
10 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
11 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
12 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
13 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
14 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
15 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
16 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
17 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
18 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
19 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
20 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
21 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
22 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
23 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
24 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8201332346410066
0.6996291718170581
0.04615700311261763
25 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9683257918552036
0.9394313967861557
0.2827071830332154
26 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
27 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
28 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9821428571428571
0.965389369592089
0.4321583502625548
29 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9544554455445544
0.9147095179233622
0.3263178509930108
30 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
31 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9756722151088348
0.9530284301606922
0.29804597061420124
32 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.7162714636140638
0.5710754017305315
0.13756596235448038
33 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
34 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
35 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
36 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
37 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
38 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
39 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
40 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
41 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
42 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
43 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
44 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
45 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
46 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
47 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
48 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.01, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
49 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
50 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
51 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
52 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
53 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
54 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.0
0.037082818294190356
0.0
55 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
56 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
57 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9794344473007712
0.9604449938195303
0.46358852448812143
58 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
59 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9741267787839586
0.9505562422744128
0.4258335400704653
60 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 300, 'neuron_layers': [4096, 2048, 1024, 512, 256, 128], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.96816114359974
0.9394313967861557
0.3615152877341416
61 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [5000, 2500], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.961412688031393
0.927070457354759
0.32231707463193865
62 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [8192, 4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.8359087564385578
0.7243510506798516
0.13806327828765858
63 / 192
{'act_fun': <function selu at 0x7f97a88ab560>, 'batch_size': 256, 'dropout_frac': 0.15, 'lr': 0.0001, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'optimizer': <class 'torch.optim.adamw.AdamW'>, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0.0001}
0.9811083123425692
0.9629171817058096
0.0
64 / 192

,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
56,<function selu at 0x7f97a88ab560>,256,0.15,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.979434,0.960445,0.463589
27,<function selu at 0x7f97a88ab560>,256,0.00,0.0001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.982143,0.965389,0.432158
90,<function selu at 0x7f97a88ab560>,256,0.30,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974127,0.950556,0.425834
58,<function selu at 0x7f97a88ab560>,256,0.15,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974127,0.950556,0.425834
91,<function selu at 0x7f97a88ab560>,256,0.30,0.0001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974160,0.950556,0.407846
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
73,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
74,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
96,<function selu at 0x7f97a88ab560>,256,0.45,0.1000,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.000000,0.037083,0.000000
189,<function selu at 0x7f97a88ab560>,256,0.90,0.0001,500,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.978535,0.957973,-0.013833

In [29]:
df_batch_ult_onecycle

,act_fun,batch_size,dropout_frac,lr,n_epochs,neuron_layers,optimizer,patience,tol,weight_decay,F1,Acc,MCC
56,<function selu at 0x7f97a88ab560>,256,0.15,0.0001,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.979434,0.960445,0.463589
27,<function selu at 0x7f97a88ab560>,256,0.00,0.0001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.982143,0.965389,0.432158
90,<function selu at 0x7f97a88ab560>,256,0.30,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974127,0.950556,0.425834
58,<function selu at 0x7f97a88ab560>,256,0.15,0.0001,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974127,0.950556,0.425834
91,<function selu at 0x7f97a88ab560>,256,0.30,0.0001,300,"[4096, 2048, 1024, 512, 256, 128]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.974160,0.950556,0.407846
...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
73,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
74,<function selu at 0x7f97a88ab560>,256,0.30,0.0100,300,"[4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.981108,0.962917,0.000000
96,<function selu at 0x7f97a88ab560>,256,0.45,0.1000,300,"[5000, 2500]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.000000,0.037083,0.000000
189,<function selu at 0x7f97a88ab560>,256,0.90,0.0001,500,"[8192, 4096, 2048, 1024, 512, 256]",<class 'torch.optim.adamw.AdamW'>,75,0.00001,0.0001,0.978535,0.957973,-0.013833