In [1]:
import os
import qsprpred
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.descriptors.sets import RDKitDescs

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [2]:
def load_datasets(path):
    dataset = QSPRDataset.fromTableFile(
    filename=path,
    store_dir="dataset_outputs/A2AR/data",
    name="A2ARDataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
    )
    dataset.prepareDataset(
    feature_calculators=[MorganFP(radius=2, nBits=1024)],
    recalculate_features=True,
    shuffle=False
    )
    from qsprpred.data.descriptors.sets import RDKitDescs
    
    rdkit_descs = RDKitDescs()
    
    dataset.addDescriptors([rdkit_descs])
    
    dataset.descriptorSets
    return dataset

In [3]:
import torch
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import RobertaTokenizerFast, RobertaForMaskedLM, DataCollatorWithPadding
from sklearn.base import BaseEstimator, TransformerMixin

class SMILESDataset(Dataset):
    def __init__(self, smiles, tokenizer, max_len=128):
        self.smiles = smiles
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.smiles)

    def __getitem__(self, idx):
        smile = self.smiles[idx]
        encoding = self.tokenizer(smile, truncation=True, padding='max_length', max_length=self.max_len, return_tensors='pt')
        return encoding


class ChemBERTaTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, model_name="entropy/roberta_zinc_480m", max_len=128, batch_size=32, device=None):
        self.model_name = model_name
        self.max_len = max_len
        self.batch_size = batch_size
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.model = RobertaForMaskedLM.from_pretrained(self.model_name).to(self.device)
        self.tokenizer = RobertaTokenizerFast.from_pretrained(self.model_name, max_len=self.max_len)
        self.collator = DataCollatorWithPadding(self.tokenizer, padding=True, return_tensors='pt')
        self.embedding_dim = None  # bude nastaven po fit()

    def fit(self, X, y=None):
        # Zjistíme embedding dimenzi na prvním SMILES
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=1, collate_fn=self.collator)
        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                embedding = outputs[1][-1]  # poslední hidden state
                self.embedding_dim = embedding.shape[-1]
                break
        return self

    def transform(self, X):
        self.model.eval()
        smiles_dataset = SMILESDataset(X, self.tokenizer, max_len=self.max_len)
        dataloader = DataLoader(smiles_dataset, batch_size=self.batch_size, collate_fn=self.collator)
        embeddings_list = []

        with torch.no_grad():
            for batch in dataloader:
                input_ids = batch['input_ids'].squeeze(1).to(self.device)
                attention_mask = batch['attention_mask'].squeeze(1).to(self.device)
                outputs = self.model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)
                full_embeddings = outputs[1][-1]
                embeddings = ((full_embeddings * attention_mask.unsqueeze(-1)).sum(1) / attention_mask.sum(-1).unsqueeze(-1))
                embeddings_list.append(embeddings)

        all_embeddings = torch.cat(embeddings_list, dim=0).cpu().numpy()
        column_names = [f"chemberta_{i}" for i in range(self.embedding_dim)]
        return pd.DataFrame(all_embeddings, columns=column_names)

In [4]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X1_all = load_datasets("CK1/data/ck1_train_1")

X2_all = load_datasets("CK1/data/ck1_val_1")

X3_all = load_datasets("CK1/data/ck1_test_1")

#transformer = ChemBERTaTransformer()
#X_train_emb = transformer.fit_transform(X1_all.df["Drug"])
#X_val_emb = transformer.transform(X2_all.df["Drug"])
#X_test_emb = transformer.transform(X3_all.df["Drug"])

In [5]:
display(X2_all.df)

,QSPRID,Y,Drug,Y_original
QSPRID,,,,
A2ARDataset_000,A2ARDataset_000,False,COc1cc(C)c(NC(=O)CN(C)C)cc1Nc1nc(Nc2cccc(F)c2C...,False
A2ARDataset_001,A2ARDataset_001,False,CC(C)(C)c1cc(NC(=O)C(=O)c2cccc3ccccc23)n(-c2cc...,False
A2ARDataset_002,A2ARDataset_002,False,Nc1nnc(-c2cc3c(Oc4ccc(Cl)cc4)cncc3s2)o1,False
A2ARDataset_003,A2ARDataset_003,False,OCc1ccc(-c2nc(-c3ccccn3)c(-c3ccc4c(c3)OCO4)[nH...,False
A2ARDataset_004,A2ARDataset_004,False,CS(=O)(=O)CCNCc1ccoc1-c1ccc2ncnc(Nc3ccc(OCc4cc...,False
...,...,...,...,...
A2ARDataset_150,A2ARDataset_150,False,COc1cc2nc3nc(-c4cccs4)c(-c4cccs4)nc3nc2cc1OC,False
A2ARDataset_151,A2ARDataset_151,False,NC1(C(=O)NCc2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1,False
A2ARDataset_152,A2ARDataset_152,False,CCc1cccc(NC(=O)Nc2ccc(Oc3ccc4nc(NC(=O)OC)[nH]c...,False
A2ARDataset_153,A2ARDataset_153,True,CC(C)CCN1c2nc(Nc3cc(F)c(O)c(F)c3)ncc2N(C)C(=O)C1C,True
A2ARDataset_154,A2ARDataset_154,True,CC(C)(C)n1nc(-c2ccc(Cl)cc2)c2c(N)ncnc21,True

In [6]:
from MolEval import MolEmb 
model_name = 'RoBERTa_ZINC'  # Replace with the model you want to use

X1_all.df["SMILES"] = X1_all.df["Drug"]
extractor = MolEmb.EmbeddingExtractor(model_name=model_name, df=X1_all.df)
emb, X1_all.df = extractor.get_embeddings()
print(emb)

No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-lightning dependency, missing a dependency. No module named 'lightning'
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'
Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

          0         1         2         3         4         5         6    \
0    0.839525  0.657080  0.260560 -0.284325 -0.212575 -0.259249 -0.536546
1    0.521116  0.330557  0.510996 -0.643829 -0.374516 -0.092652  0.079537
2    0.406173  0.094941  0.932744 -1.015941 -0.701294  0.265186 -0.147850
3    0.181259  0.227875  0.667421 -0.794918 -0.201879  0.051985  0.281510
4    0.012582  0.105825  0.637197 -0.452851 -0.308520 -0.366891 -0.377147
..        ...       ...       ...       ...       ...       ...       ...
483  0.908416  0.707765  0.471640 -0.101745 -0.161899 -0.017486  0.037784
484  0.649540  0.024394  0.535391 -0.161667 -0.518024 -0.034655  0.029912
485  0.412816  0.103349  0.281799 -0.509588 -0.296525 -0.247597  0.082339
486  0.245203  0.240351  0.940617 -0.664254 -0.599859 -0.140781  0.080944
487  0.653194  0.268082  0.447387 -0.735508 -0.328048 -0.057711  0.090916

          7         8         9    ...       758       759       760  \
0   -0.096023  0.289019  0.167203  ... -0.143628  0.515095 -0.074862
1   -0.253129  0.481151  0.327426  ...  0.051274  0.277398 -0.593216
2   -0.031923  0.124874  0.458915  ... -0.086957  0.134045  0.056459
3   -0.362835  0.258023 -0.065262  ... -0.250937  0.206534 -0.223312
4   -0.303533  0.564893 -0.705032  ...  0.054637  0.027199 -0.383653
..        ...       ...       ...  ...       ...       ...       ...
483 -0.711548  0.264038 -0.414434  ...  0.259191 -0.156011 -0.657177
484 -0.263010  0.239541 -0.105540  ...  0.279238  0.092157 -0.210265
485 -0.495882  0.210221 -0.179700  ... -0.088278  0.292331 -0.240328
486 -0.272386  0.534067  0.351494  ...  0.253126  0.356655 -0.030671
487 -0.235266  0.471851  0.436699  ... -0.044411  0.187768 -0.620578

          761       762       763       764       765       766       767
0   -0.102673  0.103030  0.130476  0.499113 -0.214322 -0.077564 -0.431823
1    0.042848 -0.011813  0.098258  0.729520 -0.701225  0.259042 -0.592370
2   -0.335765  0.136977  0.272289  1.180151 -0.274104  0.327263 -0.534128
3    0.343322 -0.241193  0.214450  1.021452 -0.288710 -0.215809 -0.786897
4    0.068650  0.585950 -0.025223  0.926432  0.213663 -0.226463 -0.451652
..        ...       ...       ...       ...       ...       ...       ...
483  0.090683 -0.131137 -0.044086  0.658195 -0.148066 -0.333033 -0.870234
484 -0.054687  0.159311  0.148841  1.103577 -0.306556  0.361056 -0.596046
485 -0.308141 -0.375836 -0.005479  0.483670 -0.645472  0.012842 -0.240922
486 -0.108964  0.162669  0.056533  0.501798 -0.532637 -0.328418 -0.128803
487  0.031293  0.052853  0.135566  0.778522 -0.409223  0.325615 -0.688533

[488 rows x 768 columns]

In [7]:
X2_all.df["SMILES"] = X2_all.df["Drug"]
extractor2 = MolEmb.EmbeddingExtractor(model_name=model_name, df=X2_all.df)
emb2, X2_all.df = extractor2.get_embeddings()
print(emb2)

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

          0         1         2         3         4         5         6    \
0    0.624928  0.242250  0.854679 -0.867963 -0.678615  0.090217 -0.139854
1    0.374832  0.298939  0.985079 -0.960167 -0.591621  0.100837  0.483177
2    0.431647  0.437582  0.698591 -0.589104 -0.381413 -0.372015  0.105332
3    0.208212  0.726000  0.748835 -0.645130 -0.163467 -0.498499 -0.233751
4    0.726675 -0.141403  0.820797 -0.664847 -0.127350 -0.111642 -0.066923
..        ...       ...       ...       ...       ...       ...       ...
150  0.087181  0.772850  0.894351 -0.344389 -0.262052 -0.413850 -0.225824
151  0.600678  0.260839  0.673289 -0.940044 -0.124541  0.322733 -0.055883
152  0.365983 -0.121044  1.093334 -0.537752 -0.664956  0.099662  0.120994
153  0.325634  0.358863  0.697016 -0.559271 -0.433622 -0.195402  0.131260
154  0.256436  0.172304  0.093762 -0.253850  0.268059 -0.568010 -0.210785

          7         8         9    ...       758       759       760  \
0   -0.456376  0.365154  0.102602  ... -0.160620  0.230485 -0.263681
1   -0.514184  0.081112 -0.036718  ...  0.086489  0.322726 -0.310237
2    0.016126  0.419026  0.467595  ...  0.035823  0.167362 -0.433423
3   -0.275675  0.498595  0.239124  ...  0.105951  0.025249 -0.059851
4   -0.472738  0.154280  0.068929  ...  0.155326  0.251512 -0.274766
..        ...       ...       ...  ...       ...       ...       ...
150 -0.605500  0.422506  0.395099  ...  0.269739  0.078071 -0.294383
151 -0.230518  0.451490 -0.312513  ...  0.185444  0.067330 -0.201065
152 -0.516345  0.295345  0.280843  ...  0.158011  0.179584 -0.359837
153  0.087071  0.553624 -0.116913  ... -0.140746  0.202888 -0.370624
154  0.075671  0.034075  0.100490  ...  0.060296  0.059718 -0.516339

          761       762       763       764       765       766       767
0   -0.565322  0.152238  0.453253  1.078272 -0.581477 -0.351562 -0.548172
1   -0.213189  0.255174 -0.006288  0.675269 -0.309778  0.443007 -0.872722
2    0.205981 -0.010362  0.084226  0.835776 -0.102376  0.034455 -0.529700
3    0.195589  0.053872 -0.013458  0.434167 -0.095912  0.032065 -0.632685
4   -0.096163 -0.007197  0.296403  0.830893 -0.167375  0.300061 -0.861038
..        ...       ...       ...       ...       ...       ...       ...
150  0.728949 -0.457967  0.072138  0.377833 -0.547883 -0.014865 -0.573838
151 -0.469250  0.165926  0.084891  0.874900 -0.314675 -0.062703 -0.665469
152 -0.009297 -0.002829  0.065308  0.727929 -0.474106  0.115676 -0.461612
153 -0.340447  0.601488 -0.022932  1.021829 -0.064751 -0.166953 -0.500140
154 -0.078960  0.372638 -0.117332  0.660407 -0.602882  0.343016 -0.861657

[155 rows x 768 columns]

In [8]:
X3_all.df["SMILES"] = X3_all.df["Drug"]
extractor3 = MolEmb.EmbeddingExtractor(model_name=model_name, df=X3_all.df)
emb3, X3_all.df = extractor3.get_embeddings()
print(emb3)

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

          0         1         2         3         4         5         6    \
0    0.279015  0.172189  0.993353 -0.794624 -0.272241  0.118495  0.194195
1    0.304655  0.057044  0.914615 -0.915091 -0.532769  0.068886  0.277302
2    0.672505  0.671482  0.135650 -0.781623 -0.451101 -0.612638  0.023349
3    0.275461  0.193600  1.067724 -0.826211 -0.143357  0.060240  0.260925
4    0.095226  0.187408  0.568077 -0.693950 -0.104264 -0.026288 -0.006962
..        ...       ...       ...       ...       ...       ...       ...
159  0.781352  0.516321  0.880270 -0.814452 -0.820508 -0.068080  0.047210
160  0.485748  0.336550  0.648807 -0.620136 -0.627679 -0.359975 -0.102899
161  0.522189  0.404734  0.003024 -0.593466 -0.324957 -0.540067 -0.465106
162  0.468361  0.274435 -0.004998 -0.569882  0.013079 -0.137342 -0.440621
163  0.803913  0.319314  0.522068 -0.561394 -0.389965 -0.444372 -0.243592

          7         8         9    ...       758       759       760  \
0   -0.341337  0.352408 -0.080742  ...  0.010942  0.226891 -0.549037
1   -0.369549  0.239993 -0.038654  ... -0.014316  0.385896 -0.545804
2   -0.251082  0.436335 -0.225284  ...  0.153847  0.328493  0.075381
3   -0.263756  0.027680  0.316482  ...  0.043420  0.275199 -0.554195
4   -0.332271  0.271738 -0.004418  ... -0.297946  0.241099 -0.360677
..        ...       ...       ...  ...       ...       ...       ...
159 -0.373809 -0.013127  0.294669  ...  0.349798  0.256530 -0.020947
160 -0.230885  0.378145  0.615476  ...  0.083183  0.174510 -0.304669
161 -0.299526 -0.068413  0.185397  ... -0.268816  0.230295 -0.299570
162 -0.439796 -0.089799 -0.146868  ... -0.106652  0.258743 -0.016806
163 -0.139057  0.313139  0.516069  ... -0.000420  0.137074 -0.281582

          761       762       763       764       765       766       767
0    0.132376  0.037968  0.605839  0.911198 -0.137456  0.129961 -0.967576
1    0.038958  0.287735  0.626203  1.166353 -0.095385 -0.005796 -0.972924
2    0.357536 -0.166716  0.382348  1.111882 -0.605728  0.704239 -0.395475
3   -0.329015 -0.197298  0.412721  0.569449 -0.312527 -0.098183 -0.531841
4    0.370727 -0.181313  0.198411  1.087878 -0.556719 -0.322968 -0.667929
..        ...       ...       ...       ...       ...       ...       ...
159 -0.335571 -0.034310  0.108234  0.765672 -0.501721 -0.253853 -0.082646
160 -0.249486  0.221935 -0.219294  0.534043 -0.708747 -0.097672  0.005163
161  0.210466  0.212637 -0.155051  0.824359 -0.204696  0.053603 -0.599155
162 -0.088005  0.264663 -0.236336  0.674913 -0.257922  0.189105 -0.678619
163 -0.294153  0.279158 -0.250988  0.684757 -0.736332  0.065020 -0.067626

[164 rows x 768 columns]

In [9]:
import pandas as pd
X1_all.X = X1_all.X.reset_index(drop=True)
emb = emb.reset_index(drop=True)
X1_all.X = pd.concat([X1_all.X, emb], axis = 1)

In [10]:
display(X1_all.X)

,MorganFP_MorganFP_0,MorganFP_MorganFP_1,MorganFP_MorganFP_2,MorganFP_MorganFP_3,MorganFP_MorganFP_4,MorganFP_MorganFP_5,MorganFP_MorganFP_6,MorganFP_MorganFP_7,MorganFP_MorganFP_8,MorganFP_MorganFP_9,...,758,759,760,761,762,763,764,765,766,767
0,False,False,False,False,False,False,False,False,False,False,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,False,False,False,False,False,False,False,False,False,False,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,False,True,False,False,False,False,False,False,False,False,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,False,False,False,False,False,False,False,False,False,False,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
4,False,False,False,True,False,False,False,False,False,False,...,0.054637,0.027199,-0.383653,0.068650,0.585950,-0.025223,0.926432,0.213663,-0.226463,-0.451652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,False,False,False,False,False,False,False,False,False,False,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
484,False,False,False,False,False,False,False,False,False,False,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
485,False,False,False,False,False,False,False,False,True,False,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
486,False,False,False,False,False,False,False,False,False,False,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
487,False,False,False,False,False,False,False,False,False,False,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

In [11]:
X2_all.X = X2_all.X.reset_index(drop=True)
emb2 = emb2.reset_index(drop=True)
X2_all.X = pd.concat([X2_all.X, emb2], axis = 1)
X3_all.X = X3_all.X.reset_index(drop=True)
emb3 = emb3.reset_index(drop=True)
X3_all.X = pd.concat([X3_all.X, emb3], axis = 1)

In [12]:
X1 = X1_all.X
y1 = X1_all.y
X2 = X2_all.X
y2 = X2_all.y
X3 = X3_all.X
y3 = X3_all.y

In [14]:
X1.columns = X1.columns.astype(str)
X2.columns = X2.columns.astype(str)
X3.columns = X3.columns.astype(str)

imp_mean = SimpleImputer(missing_values=pd.NA, strategy='mean')
X1 = imp_mean.fit_transform(X1)
X2 = imp_mean.transform(X2)
X3 = imp_mean.transform(X3)
scaler = StandardScaler()
scaler.fit(X1)
X1 = scaler.transform(X1)
X2 = scaler.transform(X2)
X3 = scaler.transform(X3)

In [15]:
pd.DataFrame(X1).columns[pd.DataFrame(X1).isna().any()].tolist()

[]

In [16]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(sampling_strategy=0.5, random_state=42)
X1, y1 = smote.fit_resample(X1, y1)
display(pd.DataFrame(X1))

,0,1,2,3,4,5,6,7,8,9,...,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001
0,-0.090909,-0.367265,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-0.867205,1.562896,0.740015,-0.007128,0.302925,0.290817,-1.193038,0.389139,-0.488945,0.195620
1,-0.090909,-0.367265,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-0.010128,0.448418,-1.361342,0.603047,-0.248245,0.183608,-0.284350,-1.654110,0.848054,-0.329638
2,-0.090909,2.722828,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-0.617997,-0.223713,1.272376,-0.984487,0.465849,0.762727,1.492864,0.138268,1.119030,-0.139089
3,-0.090909,-0.367265,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-1.339098,0.116163,0.138212,1.862946,-1.349126,0.570258,0.866983,0.076975,-1.038054,-0.966066
4,-0.090909,-0.367265,-0.090909,4.053217,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,0.004662,-0.724673,-0.511796,0.711238,2.620634,-0.227298,0.492240,2.185144,-1.080374,0.130745
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
590,-0.090909,-0.367265,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,0.718201,-1.459092,-0.386883,-1.513504,-1.252674,-2.065734,1.243633,0.522379,0.473160,0.724154
591,3.466833,-0.367265,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,0.801147,-1.028012,-0.336019,-1.439344,-1.121564,-1.984826,1.271150,0.336867,0.342815,0.574947
592,-0.090909,0.209094,-0.090909,0.555300,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-0.263113,0.870566,0.721030,-0.434983,-0.480444,0.155048,0.349936,-1.240762,-0.779169,0.998289
593,-0.090909,-0.367265,-0.090909,-0.246718,0.0,6.992298,0.0,-0.090909,-0.251358,-0.111571,...,-1.788570,-0.132143,-0.171981,-1.256847,-0.091292,0.619600,-1.287512,0.745633,-0.119099,0.476873
594,-0.090909,1.458649,-0.090909,-0.246718,0.0,-0.137074,0.0,-0.090909,-0.251358,-0.111571,...,-0.172014,-1.111876,-0.673435,0.190597,-0.402573,0.019840,-0.102192,-0.442436,0.855971,-0.661643

In [17]:

# Přidejte cestu k vašemu lokálnímu repozitáři
import sys
import os

# Přidání cesty k lokálnímu repozitáři na začátek sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Zkontrolujte, zda je cesta v sys.path
print(sys.path)

from importlib import reload

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected
# Znovu načtěte modul, abyste zajistili, že je správně importován
reload(sys.modules['qsprpred.extra.gpu.models.neural_network'])

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected

os.chdir('/home/ubuntu/Bakalarka/QSPRpred')
print(os.getcwd())


import sys
import importlib.util

# Přidání cesty k repozitáři do sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Specifikujte cestu k souboru, který chcete importovat
module_path = '/home/ubuntu/Bakalarka/QSPRpred/qsprpred/extra/gpu/models/neural_network.py'
module_name = 'qsprpred.extra.gpu.models.neural_network'

# Načtěte modul z konkrétní cesty
spec = importlib.util.spec_from_file_location(module_name, module_path)
neural_network = importlib.util.module_from_spec(spec)
spec.loader.exec_module(neural_network)

# Nyní můžete používat třídu STFullyConnected
STFullyConnected = neural_network.STFullyConnected

['/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python311.zip', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/lib-dynload', '', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages']
/home/ubuntu/Bakalarka/QSPRpred
lol

In [18]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score, matthews_corrcoef
import pandas as pd

def test_fun(dic,  X_train, y_train, X_test, y_test) -> pd.DataFrame:
    param_grid_t = ParameterGrid(dic)
    i = 0
    val_f1_t = []
    val_acc_t = []
    val_mcc_t = []
    param_len_t = len(param_grid_t)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print("Device used:", device)
    for param in param_grid_t:
        i += 1
        print(i, '/', param_len_t)
        model_sts_t = STFullyConnected(n_dim=X_train.shape[1],  # počet vstupních neuronů (počet deskriptorů)
        n_class=1,  # regresní úloha (1 výstup)
        gpus=[],
        device=device,
        is_reg=False, **param)
        model_sts_t.fit(X_train, y_train)
        res = model_sts_t.predict(X_test)
        res = res >0.5
        val_f1_t.append(f1_score(res, y_test))
        val_acc_t.append(accuracy_score(res, y_test))
        val_mcc_t.append(matthews_corrcoef(res, y_test))
        print(param)
        print(f1_score(res, y_test))
        print(accuracy_score(res, y_test))
        print(matthews_corrcoef(res, y_test))
    my_df = pd.DataFrame(param_grid_t)
    my_df["F1"] = val_f1_t
    my_df["Acc"] = val_acc_t
    my_df["MCC"] = val_mcc_t
    return my_df

In [19]:
import optuna
from sklearn.metrics import f1_score, accuracy_score, matthews_corrcoef
import torch
import torch.nn.functional as F
import torch.optim as optim
from sklearn.metrics import confusion_matrix
def objective(trial, X_train, y_train, X_test, y_test):
    dropout_frac = trial.suggest_categorical("dropout_frac", [0, 0.1, 0.2, 0.4, 0.5, 0.6, 0.8, 0.9])
    patience = trial.suggest_categorical("patience", [10, 40, 75])
    tol = trial.suggest_categorical("tol", [1e-5, 1e-4, 1e-3, 1e-2, 0])
    weight_decay = trial.suggest_categorical("weight_decay", [1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 0])
    n_epochs = trial.suggest_categorical("n_epochs", [200, 300, 500, 1000])
    batch_size = trial.suggest_categorical("batch_size", [1024, 512, 256, 128, 64])
    optimizer = trial.suggest_categorical("optimizer", ["optim.AdamW", "optim.RMSprop"])
    lr = trial.suggest_categorical("lr", [1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6])
    neuron_layers_dict = {
    '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]': [4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8],
    '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]': [2048, 1024, 512, 256, 128, 64, 32, 16, 8],
    '[4096, 1024, 256, 64, 8]': [4096, 1024, 256, 64, 8],
    '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]': [4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8],
    '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]': [4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096],
    '[200]': [200],
    '[2000]': [2000],
    '[2000, 1000]': [2000, 1000],
    '[2000, 1000, 500]': [2000, 1000, 500],
    '[1000, 50]': [1000, 50],
    '[4000, 2000]': [4000, 2000],
    '[4000, 2000, 1000, 500]': [4000, 2000, 1000, 500],
    '[4000, 2000, 2000, 500]': [4000, 2000, 2000, 500]
    }
    neuron_layers_size = trial.suggest_categorical("neuron_layers_size", list(neuron_layers_dict.keys()))
    opt = {"optim.AdamW": optim.AdamW,
           "optim.RMSprop": optim.RMSprop}
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(device)
    
    # Model
    model = STFullyConnected(
        n_dim=X_train.shape[1],
        n_class=1,
        gpus=[],
        device=device,
        is_reg=False,
        act_fun=F.selu,
        dropout_frac=dropout_frac,
        patience=patience,
        tol=tol,  # Opraveno: nyní používáme hodnotu z trial
        weight_decay=weight_decay,
        n_epochs=n_epochs,
        neuron_layers= neuron_layers_dict[neuron_layers_size],  # Použití neuron_layers_size
        batch_size=batch_size,
        optimizer=opt[optimizer],
        lr=lr,
        random_seed=69
    )
    # Trénink a predikce
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    preds_bin = preds > 0.5

    # Metiky
    f1 = f1_score(y_test, preds_bin)
    acc = accuracy_score(y_test, preds_bin)
    mcc = matthews_corrcoef(y_test, preds_bin)
    
    # Můžeš logovat i do trialu
    trial.set_user_attr("f1", f1)
    trial.set_user_attr("acc", acc)
    display(confusion_matrix(y_test, preds_bin))
    return mcc  # maximalizujeme MCC

In [ ]:
study_3 = optuna.create_study(
    study_name="CK1_new_roberta",  # jméno pro pozdější načtení
    direction="maximize",
    sampler=optuna.samplers.NSGAIISampler(),
    storage="sqlite:///optuna_results.db",
    load_if_exists=True  # pokud už existuje, nepřepíše ji
)

# Spusť optimalizaci
study_3.optimize(
    lambda trial: objective(trial, X1, y1, X2, y2),
    n_trials=200
)
print("Best MCC:", study_3.best_value)
print("Best parameters:", study_3.best_params)

# Pokud chceš F1 a ACC u nejlepšího modelu:
print("Best F1:", study_3.best_trial.user_attrs["f1"])
print("Best ACC:", study_3.best_trial.user_attrs["acc"])

[I 2025-05-03 15:31:30,839] A new study created in RDB with name: CK1_new_roberta

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:32:03,340] Trial 0 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 0 with value: 0.0.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:32:20,368] Trial 1 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.01, 'weight_decay': 1e-06, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 0 with value: 0.0.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:32:33,590] Trial 2 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[200]'}. Best is trial 0 with value: 0.0.

cuda

array([[71, 54],
       [14, 16]])

[I 2025-05-03 15:32:58,223] Trial 3 finished with value: 0.0804469308517944 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000]'}. Best is trial 3 with value: 0.0804469308517944.

cuda

array([[76, 49],
       [ 8, 22]])

[I 2025-05-03 15:33:05,048] Trial 4 finished with value: 0.2706608980034351 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000]'}. Best is trial 4 with value: 0.2706608980034351.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:34:03,680] Trial 5 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 4 with value: 0.2706608980034351.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:34:49,249] Trial 6 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0.001, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 4 with value: 0.2706608980034351.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:35:06,764] Trial 7 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 4 with value: 0.2706608980034351.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:35:14,442] Trial 8 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 4 with value: 0.2706608980034351.

cuda

array([[111,  14],
       [ 15,  15]])

[I 2025-05-03 15:35:58,261] Trial 9 finished with value: 0.39306383575945725 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[200]'}. Best is trial 9 with value: 0.39306383575945725.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:36:17,630] Trial 10 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 9 with value: 0.39306383575945725.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:36:25,074] Trial 11 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.001, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 9 with value: 0.39306383575945725.

cuda

array([[66, 59],
       [13, 17]])

[I 2025-05-03 15:37:27,701] Trial 12 finished with value: 0.07481563690005766 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 9 with value: 0.39306383575945725.

cuda

array([[104,  21],
       [ 11,  19]])

[I 2025-05-03 15:37:44,643] Trial 13 finished with value: 0.4201466272693345 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:37:55,618] Trial 14 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:38:05,491] Trial 15 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 40, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:38:12,199] Trial 16 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4000, 2000, 2000, 500]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:38:25,197] Trial 17 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[57, 68],
       [ 7, 23]])

[I 2025-05-03 15:38:55,314] Trial 18 finished with value: 0.17867350562330614 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[108,  17],
       [ 15,  15]])

[I 2025-05-03 15:40:15,096] Trial 19 finished with value: 0.3552953082965788 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:40:43,147] Trial 20 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 13 with value: 0.4201466272693345.

cuda

array([[118,   7],
       [ 16,  14]])

[I 2025-05-03 15:41:25,525] Trial 21 finished with value: 0.4740706191139998 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:41:51,505] Trial 22 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[108,  17],
       [ 14,  16]])

[I 2025-05-03 15:41:59,543] Trial 23 finished with value: 0.3834720801194842 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:42:10,397] Trial 24 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:42:55,942] Trial 25 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 0, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[109,  16],
       [ 17,  13]])

[I 2025-05-03 15:43:28,561] Trial 26 finished with value: 0.30931827625056946 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.01, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[80, 45],
       [11, 19]])

[I 2025-05-03 15:43:41,868] Trial 27 finished with value: 0.21932975241184288 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:44:31,708] Trial 28 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:45:00,700] Trial 29 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:45:08,249] Trial 30 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[1000, 50]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:45:43,620] Trial 31 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.01, 'weight_decay': 1e-06, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:47:48,822] Trial 32 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.01, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:48:05,011] Trial 33 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.1, 'n_epochs': 1000, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[96, 29],
       [12, 18]])

[I 2025-05-03 15:48:16,300] Trial 34 finished with value: 0.3163025155193633 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:48:31,906] Trial 35 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:48:48,784] Trial 36 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[109,  16],
       [ 13,  17]])

[I 2025-05-03 15:48:58,513] Trial 37 finished with value: 0.423363471004397 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[86, 39],
       [11, 19]])

[I 2025-05-03 15:49:16,614] Trial 38 finished with value: 0.2623442495522565 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[100,  25],
       [ 13,  17]])

[I 2025-05-03 15:49:23,100] Trial 39 finished with value: 0.32592914499510656 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[96, 29],
       [ 9, 21]])

[I 2025-05-03 15:49:28,050] Trial 40 finished with value: 0.39553219121294575 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[115,  10],
       [ 19,  11]])

[I 2025-05-03 15:50:09,017] Trial 41 finished with value: 0.3309259191867206 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:50:20,722] Trial 42 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[69, 56],
       [12, 18]])

[I 2025-05-03 15:50:27,561] Trial 43 finished with value: 0.1202266794619832 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.001, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[106,  19],
       [ 22,   8]])

[I 2025-05-03 15:50:31,700] Trial 44 finished with value: 0.11944444444444445 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[111,  14],
       [ 14,  16]])

[I 2025-05-03 15:50:47,919] Trial 45 finished with value: 0.42133333333333334 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[113,  12],
       [ 15,  15]])

[I 2025-05-03 15:51:00,367] Trial 46 finished with value: 0.42083333333333334 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:51:19,542] Trial 47 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[116,   9],
       [ 16,  14]])

[I 2025-05-03 15:51:46,975] Trial 48 finished with value: 0.43862683481472853 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 0.001, 'weight_decay': 1e-06, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:51:52,936] Trial 49 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[103,  22],
       [ 15,  15]])

[I 2025-05-03 15:52:00,033] Trial 50 finished with value: 0.30027472533229504 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:52:05,149] Trial 51 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[97, 28],
       [11, 19]])

[I 2025-05-03 15:52:23,276] Trial 52 finished with value: 0.351829247334944 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:52:55,272] Trial 53 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[115,  10],
       [ 17,  13]])

[I 2025-05-03 15:53:09,669] Trial 54 finished with value: 0.3926895649523752 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[109,  16],
       [ 14,  16]])

[I 2025-05-03 15:53:16,803] Trial 55 finished with value: 0.3956401967844687 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:53:49,987] Trial 56 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0.01, 'weight_decay': 1e-06, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[92, 33],
       [10, 20]])

[I 2025-05-03 15:54:27,820] Trial 57 finished with value: 0.3353692910085607 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 500, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-06, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[112,  13],
       [ 14,  16]])

[I 2025-05-03 15:56:21,604] Trial 58 finished with value: 0.43493661551390117 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[106,  19],
       [ 11,  19]])

[I 2025-05-03 15:56:37,028] Trial 59 finished with value: 0.4420555456196714 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:56:51,352] Trial 60 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 1e-05, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 3072, 2048, 1536, 1024, 768, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:57:19,354] Trial 61 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[108,  17],
       [ 15,  15]])

[I 2025-05-03 15:57:29,366] Trial 62 finished with value: 0.3552953082965788 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:58:03,738] Trial 63 finished with value: 0.0 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[111,  14],
       [ 15,  15]])

[I 2025-05-03 15:58:10,222] Trial 64 finished with value: 0.39306383575945725 and parameters: {'dropout_frac': 0.6, 'patience': 40, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:58:54,074] Trial 65 finished with value: 0.0 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0, 'weight_decay': 0.001, 'n_epochs': 1000, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.01, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:59:12,384] Trial 66 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[100,  25],
       [ 13,  17]])

[I 2025-05-03 15:59:16,114] Trial 67 finished with value: 0.32592914499510656 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.01, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 15:59:22,023] Trial 68 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:59:29,580] Trial 69 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 15:59:48,686] Trial 70 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:01:06,668] Trial 71 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[105,  20],
       [ 16,  14]])

[I 2025-05-03 16:01:10,413] Trial 72 finished with value: 0.2927858357513111 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.01, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[1000, 50]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[90, 35],
       [ 9, 21]])

[I 2025-05-03 16:01:20,853] Trial 73 finished with value: 0.3454246398538787 and parameters: {'dropout_frac': 0.1, 'patience': 10, 'tol': 0, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[94, 31],
       [20, 10]])

[I 2025-05-03 16:01:25,371] Trial 74 finished with value: 0.076434598816002 and parameters: {'dropout_frac': 0.5, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.001, 'n_epochs': 200, 'batch_size': 1024, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[109,  16],
       [ 13,  17]])

[I 2025-05-03 16:01:43,172] Trial 75 finished with value: 0.423363471004397 and parameters: {'dropout_frac': 0, 'patience': 75, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[120,   5],
       [ 19,  11]])

[I 2025-05-03 16:01:54,148] Trial 76 finished with value: 0.4241828086519717 and parameters: {'dropout_frac': 0.5, 'patience': 10, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.0001, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[71, 54],
       [14, 16]])

[I 2025-05-03 16:02:10,504] Trial 77 finished with value: 0.0804469308517944 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.01, 'neuron_layers_size': '[2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[118,   7],
       [ 16,  14]])

[I 2025-05-03 16:02:20,870] Trial 78 finished with value: 0.4740706191139998 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0.001, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[106,  19],
       [ 12,  18]])

[I 2025-05-03 16:02:43,132] Trial 79 finished with value: 0.4151946819409512 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[120,   5],
       [ 23,   7]])

[I 2025-05-03 16:03:31,866] Trial 80 finished with value: 0.2858009913947233 and parameters: {'dropout_frac': 0.8, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[118,   7],
       [ 27,   3]])

[I 2025-05-03 16:03:41,866] Trial 81 finished with value: 0.07075942729929446 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 0, 'weight_decay': 1e-05, 'n_epochs': 200, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:03:48,592] Trial 82 finished with value: 0.0 and parameters: {'dropout_frac': 0.8, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0, 'n_epochs': 200, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:04:08,317] Trial 83 finished with value: 0.0 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 512, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:04:19,850] Trial 84 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[99, 26],
       [10, 20]])

[I 2025-05-03 16:04:40,288] Trial 85 finished with value: 0.39666204652286635 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[76, 49],
       [ 7, 23]])

[I 2025-05-03 16:04:54,422] Trial 86 finished with value: 0.2967941906622971 and parameters: {'dropout_frac': 0.1, 'patience': 40, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[111,  14],
       [ 15,  15]])

[I 2025-05-03 16:05:34,858] Trial 87 finished with value: 0.39306383575945725 and parameters: {'dropout_frac': 0.1, 'patience': 75, 'tol': 0.001, 'weight_decay': 0, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 16:05:56,963] Trial 88 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[105,  20],
       [ 11,  19]])

[I 2025-05-03 16:06:03,726] Trial 89 finished with value: 0.43094458243146094 and parameters: {'dropout_frac': 0.9, 'patience': 10, 'tol': 0, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 1024, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 16:06:25,151] Trial 90 finished with value: 0.0 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.0001, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[110,  15],
       [ 15,  15]])

[I 2025-05-03 16:07:15,133] Trial 91 finished with value: 0.38 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 1000, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[113,  12],
       [ 15,  15]])

[I 2025-05-03 16:07:34,612] Trial 92 finished with value: 0.42083333333333334 and parameters: {'dropout_frac': 0.9, 'patience': 75, 'tol': 0.01, 'weight_decay': 0, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-05, 'neuron_layers_size': '[4000, 2000, 1000, 500]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[94, 31],
       [14, 16]])

[I 2025-05-03 16:07:47,424] Trial 93 finished with value: 0.24524905188820198 and parameters: {'dropout_frac': 0, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.001, 'n_epochs': 300, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 0.001, 'neuron_layers_size': '[200]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:08:06,964] Trial 94 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 75, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.RMSprop', 'lr': 1e-05, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[120,   5],
       [ 30,   0]])

[I 2025-05-03 16:08:21,344] Trial 95 finished with value: -0.08944271909999159 and parameters: {'dropout_frac': 0.9, 'patience': 40, 'tol': 0.001, 'weight_decay': 0.1, 'n_epochs': 500, 'batch_size': 512, 'optimizer': 'optim.RMSprop', 'lr': 0.1, 'neuron_layers_size': '[2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 16:08:40,953] Trial 96 finished with value: 0.0 and parameters: {'dropout_frac': 0.4, 'patience': 40, 'tol': 0, 'weight_decay': 0.01, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.RMSprop', 'lr': 1, 'neuron_layers_size': '[4000, 2000]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[125,   0],
       [ 30,   0]])

[I 2025-05-03 16:09:06,078] Trial 97 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 0.0001, 'weight_decay': 0.1, 'n_epochs': 200, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 16:09:36,627] Trial 98 finished with value: 0.0 and parameters: {'dropout_frac': 0.6, 'patience': 75, 'tol': 0.001, 'weight_decay': 0.0001, 'n_epochs': 500, 'batch_size': 128, 'optimizer': 'optim.AdamW', 'lr': 0.0001, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[  0, 125],
       [  0,  30]])

[I 2025-05-03 16:10:06,515] Trial 99 finished with value: 0.0 and parameters: {'dropout_frac': 0.2, 'patience': 10, 'tol': 1e-05, 'weight_decay': 0.1, 'n_epochs': 300, 'batch_size': 64, 'optimizer': 'optim.AdamW', 'lr': 1, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 128, 64, 32, 16, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[115,  10],
       [ 16,  14]])

[I 2025-05-03 16:10:22,339] Trial 100 finished with value: 0.42229029405283497 and parameters: {'dropout_frac': 0.6, 'patience': 10, 'tol': 0.01, 'weight_decay': 0.01, 'n_epochs': 300, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 2048, 1024, 512, 256, 512, 1024, 2048, 4096]'}. Best is trial 21 with value: 0.4740706191139998.

cuda

array([[107,  18],
       [ 13,  17]])

[I 2025-05-03 16:10:42,768] Trial 101 finished with value: 0.39938245981308346 and parameters: {'dropout_frac': 0, 'patience': 40, 'tol': 0.001, 'weight_decay': 1e-05, 'n_epochs': 500, 'batch_size': 256, 'optimizer': 'optim.AdamW', 'lr': 1e-06, 'neuron_layers_size': '[4096, 1024, 256, 64, 8]'}. Best is trial 21 with value: 0.4740706191139998.

cuda