In [1]:
import os
import qsprpred

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.sampling.splits import GBMTDataSplit

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [2]:
os.makedirs("dataset_outputs/hERG/data", exist_ok=True)

# Create dataset
dataset_test = QSPRDataset.fromTableFile(
    filename="data/src/datasets/ck1/data/CK1.csv",
    store_dir="dataset_outputs/CK1/data",
    name="CK1Dataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
)

In [3]:
dataset_test.prepareDataset(
    split=GBMTDataSplit(test_fraction=0.2, dataset=dataset_test),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
)

In [4]:
display(dataset_test.X_ind.index)

Index(['CK1Dataset_004', 'CK1Dataset_014', 'CK1Dataset_018', 'CK1Dataset_021',
       'CK1Dataset_025', 'CK1Dataset_031', 'CK1Dataset_036', 'CK1Dataset_038',
       'CK1Dataset_052', 'CK1Dataset_056',
       ...
       'CK1Dataset_754', 'CK1Dataset_755', 'CK1Dataset_757', 'CK1Dataset_759',
       'CK1Dataset_765', 'CK1Dataset_767', 'CK1Dataset_770', 'CK1Dataset_775',
       'CK1Dataset_792', 'CK1Dataset_793'],
      dtype='object', name='QSPRID', length=161)

In [5]:
display(dataset_test.getDF().QSPRID)

QSPRID
CK1Dataset_000    CK1Dataset_000
CK1Dataset_001    CK1Dataset_001
CK1Dataset_002    CK1Dataset_002
CK1Dataset_003    CK1Dataset_003
CK1Dataset_004    CK1Dataset_004
                       ...
CK1Dataset_802    CK1Dataset_802
CK1Dataset_803    CK1Dataset_803
CK1Dataset_804    CK1Dataset_804
CK1Dataset_805    CK1Dataset_805
CK1Dataset_806    CK1Dataset_806
Name: QSPRID, Length: 807, dtype: object

In [6]:
dataset_1 = QSPRDataset.fromTableFile(
    filename="data/src/datasets/ck1/data/CK1.csv",
    store_dir="dataset_outputs/CK1/data",
    name="CK1Dataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41,
    smiles_col = 'Drug',
    sep=','
)

In [7]:
dataset_1.df

,Y,Drug,QSPRID,Y_original
QSPRID,,,,
CK1Dataset_000,False,CC(C)(O)c1ccc(Nc2nc3ccc(C#N)cc3[nH]2)cc1,CK1Dataset_000,0.0
CK1Dataset_001,True,CCc1nccn2c(-c3ccnc(NCC(C)(C)O)n3)c(-c3ccc(F)cc...,CK1Dataset_001,1.0
CK1Dataset_002,False,Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc...,CK1Dataset_002,0.0
CK1Dataset_003,False,CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5ccc...,CK1Dataset_003,0.0
CK1Dataset_004,False,COc1cc(C)c(NC(=O)CN(C)C)cc1Nc1nc(Nc2cccc(F)c2C...,CK1Dataset_004,0.0
...,...,...,...,...
CK1Dataset_802,False,NC1CCN(c2ncnc3[nH]ccc23)CC1,CK1Dataset_802,0.0
CK1Dataset_803,True,NC1CCCC(Nc2nc(Cl)cc(-c3c[nH]c4ncccc34)n2)C1,CK1Dataset_803,1.0
CK1Dataset_804,True,Cc1nccn2c(-c3ccnc(NCCC(C)(C)O)n3)c(-c3ccc(F)cc...,CK1Dataset_804,1.0
CK1Dataset_805,True,CC(C)CCN1c2nc(Nc3cc(F)c(O)c(F)c3)ncc2N(C)C(=O)C1C,CK1Dataset_805,1.0
CK1Dataset_806,True,CC(C)(C)n1nc(-c2ccc(Cl)cc2)c2c(N)ncnc21,CK1Dataset_806,1.0

In [8]:
dataset_1.df = dataset_1.df[~dataset_1.df.index.isin(dataset_test.X_ind.index)]

In [9]:
dataset_1.df

,Y,Drug,QSPRID,Y_original
QSPRID,,,,
CK1Dataset_000,False,CC(C)(O)c1ccc(Nc2nc3ccc(C#N)cc3[nH]2)cc1,CK1Dataset_000,0.0
CK1Dataset_001,True,CCc1nccn2c(-c3ccnc(NCC(C)(C)O)n3)c(-c3ccc(F)cc...,CK1Dataset_001,1.0
CK1Dataset_002,False,Cc1ccc(NC(=O)c2ccc(CN3CCN(C)CC3)cc2)cc1Nc1nccc...,CK1Dataset_002,0.0
CK1Dataset_003,False,CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5ccc...,CK1Dataset_003,0.0
CK1Dataset_005,False,CS(=O)(=O)CCNCc1nc(-c2ccc3ncnc(Nc4ccc(F)c(Cl)c...,CK1Dataset_005,0.0
...,...,...,...,...
CK1Dataset_802,False,NC1CCN(c2ncnc3[nH]ccc23)CC1,CK1Dataset_802,0.0
CK1Dataset_803,True,NC1CCCC(Nc2nc(Cl)cc(-c3c[nH]c4ncccc34)n2)C1,CK1Dataset_803,1.0
CK1Dataset_804,True,Cc1nccn2c(-c3ccnc(NCCC(C)(C)O)n3)c(-c3ccc(F)cc...,CK1Dataset_804,1.0
CK1Dataset_805,True,CC(C)CCN1c2nc(Nc3cc(F)c(O)c(F)c3)ncc2N(C)C(=O)C1C,CK1Dataset_805,1.0
CK1Dataset_806,True,CC(C)(C)n1nc(-c2ccc(Cl)cc2)c2c(N)ncnc21,CK1Dataset_806,1.0

In [10]:
datasets = []
for i in range(10):
    print(i)
    datasets.append(QSPRDataset.fromTableFile(
    filename="data/src/datasets/ck1/data/CK1.csv",
    store_dir="dataset_outputs/CK1/data",
    name="CK1Dataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=41,
    smiles_col = 'Drug',
    sep=','
    ))
    datasets[i].df = datasets[i].df[~datasets[i].df.index.isin(dataset_test.X_ind.index)]
    datasets[i].random_state = i
    datasets[i].prepareDataset(
    split=GBMTDataSplit(test_fraction=0.25, dataset=datasets[i]),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
    )

0
1
2
3
4
5
6
7
8
9

In [13]:
os.makedirs("CK1/data", exist_ok=True)
ind = 0
for i in datasets:
    ind += 1
    display(i.X.shape)
    train = i.df[~i.df.index.isin(i.X_ind.index)]
    df_train = train
    val = i.df[~i.df.index.isin(i.X.index)]
    df_val = val
    df_train.to_csv(f"CK1/data/ck1_train_{ind}")
    df_val.to_csv(f"CK1/data/ck1_val_{ind}")

(485, 2048)

(485, 2048)

(485, 2048)

(486, 2048)

(486, 2048)

(485, 2048)

(485, 2048)

(485, 2048)

(485, 2048)

(485, 2048)

In [14]:
herg_test = dataset_test.df[dataset_test.df.index.isin(dataset_test.X_ind.index)]
herg_test.to_csv(f"CK1/data/ck1_test")

In [ ]:
from qsprpred.data.descriptors.sets import RDKitDescs

rdkit_descs = RDKitDescs()

dataset.addDescriptors([rdkit_descs])

dataset.descriptorSets

In [ ]:
import torch
from transformers import RobertaTokenizerFast, RobertaForMaskedLM, DataCollatorWithPadding
from torch.utils.data import DataLoader, Dataset

# Nastavení zařízení (GPU nebo CPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Načtení tokenizeru a modelu
tokenizer = RobertaTokenizerFast.from_pretrained("entropy/roberta_zinc_480m", max_len=128)
model = RobertaForMaskedLM.from_pretrained('entropy/roberta_zinc_480m')

# Přenesení modelu na správné zařízení
model.to(device)

# Připravení collatoru pro padding
collator = DataCollatorWithPadding(tokenizer, padding=True, return_tensors='pt')

# Načtení seznamu SMILES (například z nějaké jiné struktury než datasetu)
smiles = ["CCO", "CC(=O)O", "CCN", "CC(C)O", "CCC", "CCCC", "CCCO"] * 100  # Příklad seznamu SMILES, můžeš použít vlastní

# Vytvoření datasetu
smiles_dataset = SMILESDataset(smiles, tokenizer)

# Vytvoření DataLoaderu (dávky po 32)
batch_size = 32
dataloader = DataLoader(smiles_dataset, batch_size=batch_size, collate_fn=collator)

# Zpracování dat po dávkách
model.eval()  # Převede model do evaluačního režimu (bez trénování)
embeddings_list = []  # Uchováme všechny embeddings

with torch.no_grad():  # Nevytvářet gradienty během evaluace
    for batch in dataloader:
        # Zkontroluj tvar batchů
        print("Batch input_ids tvar:", batch['input_ids'].shape)
        print("Batch attention_mask tvar:", batch['attention_mask'].shape)

        # Přenesení všech vstupů na správné zařízení (GPU nebo CPU)
        input_ids = batch['input_ids'].squeeze(1).to(device)  # Squeeze odstraní extra dimenzi
        attention_mask = batch['attention_mask'].squeeze(1).to(device)  # Squeeze odstraní extra dimenzi

        # Modelování výstupů s hidden states
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, output_hidden_states=True)

        # Získání poslední vrstvy hidden states
        full_embeddings = outputs[1][-1]

        # Výpočet průměrného embeddingu pro každý token
        embeddings = ((full_embeddings * attention_mask.unsqueeze(-1)).sum(1) / attention_mask.sum(-1).unsqueeze(-1))
        
        # Uložení embeddings pro tuto dávku
        embeddings_list.append(embeddings)

# Spojení všech embeddings z dávky do jednoho tensoru
all_embeddings = torch.cat(embeddings_list, dim=0)

# Teď můžeš použít `all_embeddings`, což obsahuje embeddings pro všechny SMILES v datasetu