In [66]:
import os
import qsprpred
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import torch

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP
import pandas as pd
from qsprpred.data.descriptors.sets import RDKitDescs
from MolEval import MolEmb

In [126]:
import numpy as np
import pandas as pd
from sklearn.feature_selection import VarianceThreshold
from qsprpred.data.descriptors.sets import RDKitDescs

def load_datasets(path):
    dataset = QSPRDataset.fromTableFile(
    filename=path,
    store_dir="dataset_outputs/A2AR/data",
    name="CK1Dataset",
    target_props=[{"name": "Y", "task": "SINGLECLASS", "th": [0.5]}],
    random_state=42,
    smiles_col = 'Drug',
    sep=','
    )
    return dataset

class Dataset_creator():
    def __init__(self, model_names=['RoBERTa_ZINC'], corr_thrsh= 0.95):
        self.variance = VarianceThreshold(threshold=0.0)
        self.model_names = model_names
        self.corr_thrsh = corr_thrsh
        self.selected_indices = None
        
    def fit_transform(self, dataset):
        dataset.prepareDataset(feature_calculators=[MorganFP(radius=2, nBits=4096)], recalculate_features=True, shuffle=False)
        rdkit_descs = RDKitDescs()
        dataset.addDescriptors([rdkit_descs])
        display(dataset.X.shape)
        
        dataset.descriptorSets
        dataset_embs = self.create_embs(dataset)
        dataset_embs.index = dataset.X.index
        dataset.X = pd.concat([dataset.X, dataset_embs], axis=1)
        display(dataset.X.shape)
        
        dataset_no_var_np = self.variance.fit_transform(dataset.X)
        mask = self.variance.get_support()
        dataset_without_no_var = pd.DataFrame(
            dataset_no_var_np,
            columns=dataset.X.columns[mask],
            index=dataset.X.index)
        display(dataset_without_no_var.shape)

        
        dataset_without_high_corr = self.high_correlation(dataset_without_no_var)
        display(dataset_without_high_corr.shape)
        
        dataset.X = dataset_without_high_corr
        return dataset
        
    def transform(self, dataset):
        dataset.prepareDataset(feature_calculators=[MorganFP(radius=2, nBits=4096)], recalculate_features=True, shuffle=False)
        rdkit_descs = RDKitDescs()
        dataset.addDescriptors([rdkit_descs])
        display(dataset.X.shape)

        dataset.descriptorSets
        dataset_embs = self.create_embs(dataset)
        dataset_embs.index = dataset.X.index
        dataset.X = pd.concat([dataset.X, dataset_embs], axis=1)
        display(dataset.X.shape)

        dataset_no_var_np = self.variance.transform(dataset.X)
        mask = self.variance.get_support()
        dataset_without_no_var = pd.DataFrame(
            dataset_no_var_np,
            columns=dataset.X.columns[mask],
            index=dataset.X.index)
        display(dataset_without_no_var.shape)

        dataset_without_high_corr = dataset_without_no_var[self.selected_indices]
        display(dataset_without_high_corr.shape)

        dataset.X = dataset_without_high_corr
        return dataset

    def high_correlation(self, df: pd.DataFrame):
        corr_matrix = df.corr().abs()
        upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
        
        to_drop = [column for column in upper.columns if any(upper[column] > self.corr_thrsh)]
        self.selected_indices = df.columns.difference(to_drop)
        
        return df[self.selected_indices]

        
    def create_embs(self, dataset):
        dataset.df["SMILES"] = dataset.df["Drug"]
        final_emb = pd.DataFrame()
        for model_name in self.model_names:
            extractor = MolEmb.EmbeddingExtractor(model_name=model_name, df=dataset.df)
            new_emb, dataset.df = extractor.get_embeddings()
            display(type(new_emb))
            if final_emb.empty:
                final_emb = new_emb
            else:
                final_emb = pd.concat([final_emb, new_emb], axis=1)
        final_emb.columns = final_emb.columns.astype(str)
        display(final_emb)
        return final_emb

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

X1_all = load_datasets("CK1/data/ck1_train_1")

X2_all = load_datasets("CK1/data/ck1_val_1")

X3_all = load_datasets("CK1/data/ck1_test_1")

In [4]:
cls = Dataset_creator(['Mol2Vec', 'RoBERTa_ZINC'])

In [5]:
X1_all = cls.fit_transform(X1_all)
X2_all = cls.transform(X2_all)
X3_all = cls.transform(X3_all)

(488, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
4,2.010692,-1.409427,-3.583793,3.778501,1.039966,-1.023768,-7.496891,-0.705993,5.007909,2.194638,...,0.054637,0.027199,-0.383653,0.068650,0.585950,-0.025223,0.926432,0.213663,-0.226463,-0.451652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
484,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
485,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
486,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
487,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(488, 5374)

(488, 3757)

(488, 2400)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
1,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
2,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
3,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
4,2.975206,-6.491653,-3.839927,11.821246,-0.138459,1.003587,-17.784031,-2.597596,12.989882,3.524831,...,0.155326,0.251512,-0.274766,-0.096163,-0.007197,0.296403,0.830893,-0.167375,0.300061,-0.861038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
151,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
152,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
153,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3757)

(155, 2400)

(164, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
3,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
4,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,4.732400,-5.931112,-2.695037,7.379294,0.355767,1.439902,-9.418824,-0.047803,4.838798,0.808847,...,0.349798,0.256530,-0.020947,-0.335571,-0.034310,0.108234,0.765672,-0.501721,-0.253853,-0.082646
160,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
161,2.183160,-2.231052,-2.962017,7.712423,-0.278175,0.161704,-8.929571,-0.744787,6.846818,2.309243,...,-0.268816,0.230295,-0.299570,0.210466,0.212637,-0.155051,0.824359,-0.204696,0.053603,-0.599155
162,1.697251,-2.229853,-2.875325,7.633800,-0.657874,-0.268612,-8.608117,-0.441910,7.232983,2.815516,...,-0.106652,0.258743,-0.016806,-0.088005,0.264663,-0.236336,0.674913,-0.257922,0.189105,-0.678619
163,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626

(164, 5374)

(164, 3757)

(164, 2400)

In [6]:
X1_all.X.to_csv("CK1/mod_data/X1.1")
X2_all.X.to_csv("CK1/mod_data/X2.1")
X3_all.X.to_csv("CK1/mod_data/X3.1")
X1_all.y.to_csv("CK1/mod_data/y1.1")
X2_all.y.to_csv("CK1/mod_data/y2.1")
X3_all.y.to_csv("CK1/mod_data/y3.1")

In [127]:
for i in range(2, 11):
    X1_all = load_datasets(f"CK1/data/ck1_train_{i}")

    X2_all = load_datasets(f"CK1/data/ck1_val_{i}")

    X3_all = load_datasets(f"CK1/data/ck1_test_{i}")
    cls = Dataset_creator(['Mol2Vec', 'RoBERTa_ZINC'])
    X1_all = cls.fit_transform(X1_all)
    X2_all = cls.transform(X2_all)
    X3_all = cls.transform(X3_all)

    X1_all.X.to_csv(f"CK1/mod_data/X1.{i}")
    X2_all.X.to_csv(f"CK1/mod_data/X2.{i}")
    X3_all.X.to_csv(f"CK1/mod_data/X3.{i}")
    X1_all.y.to_csv(f"CK1/mod_data/y1.{i}")
    X2_all.y.to_csv(f"CK1/mod_data/y2.{i}")
    X3_all.y.to_csv(f"CK1/mod_data/y3.{i}")

(488, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
4,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
484,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
485,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
486,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
487,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(488, 5374)

(488, 3797)

(488, 2448)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
1,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
2,2.975206,-6.491653,-3.839927,11.821246,-0.138459,1.003587,-17.784031,-2.597596,12.989882,3.524831,...,0.155326,0.251512,-0.274766,-0.096163,-0.007197,0.296403,0.830893,-0.167375,0.300061,-0.861038
3,3.421278,-4.980500,-1.818619,4.949851,2.646937,-0.494111,-14.675534,1.573397,9.757618,1.263535,...,-0.307539,0.245799,-0.106744,-0.264735,0.080338,0.211269,1.132695,-0.222763,-0.061978,-0.806557
4,3.650284,-1.422407,-3.521151,7.320927,-1.333769,2.509427,-8.297083,1.643375,5.793886,5.512853,...,-0.077185,0.191360,-0.504341,-0.058500,-0.128520,0.108197,0.814795,-0.230626,-0.438794,-0.017016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
151,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
152,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
153,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3797)

(155, 2448)

(164, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
1,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
2,3.250073,-3.554803,-2.132563,5.592683,-1.939698,-0.764838,-11.769052,0.243908,7.156982,6.107278,...,0.346624,0.561929,0.005611,-0.529639,-0.168346,-0.015580,1.096539,-0.526291,0.313751,-0.064641
3,6.422253,-6.735518,-5.210602,11.719648,-1.032450,0.334099,-14.181977,-1.368757,11.214272,3.856359,...,0.055490,0.310419,0.332255,-0.026450,-0.234644,0.049131,0.921900,-0.607951,0.257575,-0.761586
4,1.331712,-3.429876,-2.917234,9.412067,-0.096169,-0.064359,-13.828246,-1.243533,9.702394,3.003018,...,0.680291,-0.399387,0.066852,0.019135,-0.004352,-0.077583,1.282859,-0.437072,0.713512,-1.019335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,4.732400,-5.931112,-2.695037,7.379294,0.355767,1.439902,-9.418824,-0.047803,4.838798,0.808847,...,0.349798,0.256530,-0.020947,-0.335571,-0.034310,0.108234,0.765672,-0.501721,-0.253853,-0.082646
160,6.582543,-7.329996,-4.759246,12.043168,-1.987458,0.298040,-12.951245,-0.435326,11.249726,5.142750,...,0.228727,0.368913,-0.149250,-0.161376,0.047545,0.115475,0.698509,-0.352763,0.127760,-0.714638
161,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
162,7.345458,-6.355425,-4.986184,12.296846,-1.233523,-0.840597,-14.978375,-1.273263,11.056189,5.865771,...,-0.070397,0.397062,0.087383,-0.055037,-0.098290,0.215882,1.065601,-0.435961,0.015639,-0.673310
163,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(164, 5374)

(164, 3797)

(164, 2448)

(490, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
4,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
486,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
487,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
488,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
489,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(490, 5374)

(490, 3753)

(490, 2420)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
1,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
2,2.010692,-1.409427,-3.583793,3.778501,1.039966,-1.023768,-7.496891,-0.705993,5.007909,2.194638,...,0.054637,0.027199,-0.383653,0.068650,0.585950,-0.025223,0.926432,0.213663,-0.226463,-0.451652
3,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
4,3.650284,-1.422407,-3.521151,7.320927,-1.333769,2.509427,-8.297083,1.643375,5.793886,5.512853,...,-0.077185,0.191360,-0.504341,-0.058500,-0.128520,0.108197,0.814795,-0.230626,-0.438794,-0.017016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1.855299,-3.293243,-3.795229,8.895205,-1.158641,0.404485,-12.343959,-0.628700,8.777167,4.386709,...,0.213471,0.078898,-0.596568,0.018820,0.102490,0.358819,1.119211,-0.487073,0.266411,-0.664652
151,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
152,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
153,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3753)

(155, 2420)

(162, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
1,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
2,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
3,2.975206,-6.491653,-3.839927,11.821246,-0.138459,1.003587,-17.784031,-2.597596,12.989882,3.524831,...,0.155326,0.251512,-0.274766,-0.096163,-0.007197,0.296403,0.830893,-0.167375,0.300061,-0.861038
4,3.259504,-6.948333,-5.314281,16.877680,-1.561594,1.677068,-21.192827,-1.086085,15.852525,7.113788,...,0.054741,0.168013,-0.505847,0.202824,0.007140,0.245082,0.770282,0.036515,0.059159,-1.034368
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,4.080963,-6.359069,-5.269644,11.860126,-0.075333,3.266928,-18.994394,-1.355099,14.285904,4.428610,...,-0.180873,-0.124348,-0.549422,0.079085,0.075019,0.445874,0.769192,0.268825,0.107943,-0.835486
158,3.174270,-3.787992,-4.284914,10.486748,-2.209318,0.314947,-11.841339,-0.726137,10.180140,3.709490,...,0.266872,-0.009687,-0.001082,0.119847,0.311209,0.014553,0.495871,-0.220561,0.080125,-0.764630
159,3.431850,-3.951498,-3.873784,11.321042,-1.470229,-0.033905,-12.651198,-0.759370,9.544827,2.745059,...,0.332333,-0.200369,0.149653,0.110235,0.264349,-0.007880,0.597121,-0.437636,0.532644,-0.581497
160,3.543678,-4.939993,-2.745279,5.001237,3.252913,2.434391,-12.037653,-4.270888,5.143949,-0.947130,...,0.178954,-0.141457,-0.531013,-0.017829,-0.111482,0.153350,0.249961,-0.323089,0.162780,-0.450837
161,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(162, 5374)

(162, 3753)

(162, 2420)

(492, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
4,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
488,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
489,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
490,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
491,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(492, 5374)

(492, 3753)

(492, 2393)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
3,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
4,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
151,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
152,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
153,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3753)

(155, 2393)

(160, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
1,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
2,3.250073,-3.554803,-2.132563,5.592683,-1.939698,-0.764838,-11.769052,0.243908,7.156982,6.107278,...,0.346624,0.561929,0.005611,-0.529639,-0.168346,-0.015580,1.096539,-0.526291,0.313751,-0.064641
3,3.650284,-1.422407,-3.521151,7.320927,-1.333769,2.509427,-8.297083,1.643375,5.793886,5.512853,...,-0.077185,0.191360,-0.504341,-0.058500,-0.128520,0.108197,0.814795,-0.230626,-0.438794,-0.017016
4,1.331712,-3.429876,-2.917234,9.412067,-0.096169,-0.064359,-13.828246,-1.243533,9.702394,3.003018,...,0.680291,-0.399387,0.066852,0.019135,-0.004352,-0.077583,1.282859,-0.437072,0.713512,-1.019335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,4.732400,-5.931112,-2.695037,7.379294,0.355767,1.439902,-9.418824,-0.047803,4.838798,0.808847,...,0.349798,0.256530,-0.020947,-0.335571,-0.034310,0.108234,0.765672,-0.501721,-0.253853,-0.082646
156,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
157,2.183160,-2.231052,-2.962017,7.712423,-0.278175,0.161704,-8.929571,-0.744787,6.846818,2.309243,...,-0.268816,0.230295,-0.299570,0.210466,0.212637,-0.155051,0.824359,-0.204696,0.053603,-0.599155
158,1.697251,-2.229853,-2.875325,7.633800,-0.657874,-0.268612,-8.608117,-0.441910,7.232983,2.815516,...,-0.106652,0.258743,-0.016806,-0.088005,0.264663,-0.236336,0.674913,-0.257922,0.189105,-0.678619
159,3.543678,-4.939993,-2.745279,5.001237,3.252913,2.434391,-12.037653,-4.270888,5.143949,-0.947130,...,0.178954,-0.141457,-0.531013,-0.017829,-0.111482,0.153350,0.249961,-0.323089,0.162780,-0.450837

(160, 5374)

(160, 3753)

(160, 2393)

(488, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
1,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
2,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
3,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
4,2.010692,-1.409427,-3.583793,3.778501,1.039966,-1.023768,-7.496891,-0.705993,5.007909,2.194638,...,0.054637,0.027199,-0.383653,0.068650,0.585950,-0.025223,0.926432,0.213663,-0.226463,-0.451652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
484,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
485,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
486,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
487,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(488, 5374)

(488, 3740)

(488, 2390)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
1,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
2,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
3,1.793583,-1.667465,-3.564327,6.057609,-0.035985,-0.463150,-9.730979,-0.514264,8.038250,3.602887,...,0.181600,-0.296856,-0.379700,0.073864,0.108085,0.213308,0.665520,-0.383069,-0.130134,-0.055589
4,3.607882,0.627815,-2.229333,1.607389,-1.028664,0.608786,-4.680721,1.453469,2.078131,1.112946,...,-0.228876,-0.152549,-0.815032,-0.161689,-0.152988,0.435513,0.707267,0.141142,0.063063,-0.461621
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,1.853239,0.314050,-3.637548,4.493600,0.156652,2.654613,-9.141600,0.566076,3.153321,3.646094,...,0.042161,0.016015,-0.176121,0.000891,0.155261,-0.090028,1.187078,-0.366307,-0.030519,-0.431114
151,3.174270,-3.787992,-4.284914,10.486748,-2.209318,0.314947,-11.841339,-0.726137,10.180140,3.709490,...,0.266872,-0.009687,-0.001082,0.119847,0.311209,0.014553,0.495871,-0.220561,0.080125,-0.764630
152,3.431850,-3.951498,-3.873784,11.321042,-1.470229,-0.033905,-12.651198,-0.759370,9.544827,2.745059,...,0.332333,-0.200369,0.149653,0.110235,0.264349,-0.007880,0.597121,-0.437636,0.532644,-0.581497
153,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3740)

(155, 2390)

(164, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
2,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
3,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
4,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
160,2.183160,-2.231052,-2.962017,7.712423,-0.278175,0.161704,-8.929571,-0.744787,6.846818,2.309243,...,-0.268816,0.230295,-0.299570,0.210466,0.212637,-0.155051,0.824359,-0.204696,0.053603,-0.599155
161,4.080963,-6.359069,-5.269644,11.860126,-0.075333,3.266928,-18.994394,-1.355099,14.285904,4.428610,...,-0.180873,-0.124348,-0.549422,0.079085,0.075019,0.445874,0.769192,0.268825,0.107943,-0.835486
162,1.697251,-2.229853,-2.875325,7.633800,-0.657874,-0.268612,-8.608117,-0.441910,7.232983,2.815516,...,-0.106652,0.258743,-0.016806,-0.088005,0.264663,-0.236336,0.674913,-0.257922,0.189105,-0.678619
163,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(164, 5374)

(164, 3740)

(164, 2390)

(492, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
4,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
488,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
489,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
490,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
491,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(492, 5374)

(492, 3736)

(492, 2405)

(156, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
1,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
2,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
3,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
4,5.729228,-3.166988,-3.895909,5.679392,1.449330,-1.305316,-11.893211,-1.713075,4.674937,2.436722,...,0.093671,-0.063280,-0.235991,-0.252169,-0.102221,-0.001065,0.907480,-0.308638,0.059508,-0.163791
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
152,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
153,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
154,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
155,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(156, 5374)

(156, 3736)

(156, 2405)

(159, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
3,3.250073,-3.554803,-2.132563,5.592683,-1.939698,-0.764838,-11.769052,0.243908,7.156982,6.107278,...,0.346624,0.561929,0.005611,-0.529639,-0.168346,-0.015580,1.096539,-0.526291,0.313751,-0.064641
4,3.650284,-1.422407,-3.521151,7.320927,-1.333769,2.509427,-8.297083,1.643375,5.793886,5.512853,...,-0.077185,0.191360,-0.504341,-0.058500,-0.128520,0.108197,0.814795,-0.230626,-0.438794,-0.017016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,5.485065,-2.266671,-4.258873,7.732013,5.843917,-0.851230,-16.790916,-4.512785,6.257599,0.242395,...,0.026403,-0.116650,-0.050577,0.006803,-0.031684,0.320115,0.540757,-0.335199,-0.100660,-0.381148
155,4.732400,-5.931112,-2.695037,7.379294,0.355767,1.439902,-9.418824,-0.047803,4.838798,0.808847,...,0.349798,0.256530,-0.020947,-0.335571,-0.034310,0.108234,0.765672,-0.501721,-0.253853,-0.082646
156,2.875931,-3.222089,-5.788570,7.097994,0.962627,1.479316,-10.616526,-2.792910,4.344872,0.544410,...,0.142886,-0.102570,0.170256,-0.133289,-0.142881,-0.621665,1.105325,-0.584412,0.735228,-0.429748
157,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
158,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(159, 5374)

(159, 3736)

(159, 2405)

(495, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
4,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
490,3.431850,-3.951498,-3.873784,11.321042,-1.470229,-0.033905,-12.651198,-0.759370,9.544827,2.745059,...,0.332333,-0.200369,0.149653,0.110235,0.264349,-0.007880,0.597121,-0.437636,0.532644,-0.581497
491,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
492,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
493,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
494,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803

(495, 5374)

(495, 3719)

(495, 2382)

(156, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
1,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
2,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
3,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
4,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,1.853239,0.314050,-3.637548,4.493600,0.156652,2.654613,-9.141600,0.566076,3.153321,3.646094,...,0.042161,0.016015,-0.176121,0.000891,0.155261,-0.090028,1.187078,-0.366307,-0.030519,-0.431114
152,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
153,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
154,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533
155,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(156, 5374)

(156, 3719)

(156, 2382)

(156, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
1,3.259504,-6.948333,-5.314281,16.877680,-1.561594,1.677068,-21.192827,-1.086085,15.852525,7.113788,...,0.054741,0.168013,-0.505847,0.202824,0.007140,0.245082,0.770282,0.036515,0.059159,-1.034368
2,3.250073,-3.554803,-2.132563,5.592683,-1.939698,-0.764838,-11.769052,0.243908,7.156982,6.107278,...,0.346624,0.561929,0.005611,-0.529639,-0.168346,-0.015580,1.096539,-0.526291,0.313751,-0.064641
3,5.324458,-6.611471,-1.146888,8.203466,-0.377238,1.208825,-10.974276,0.238361,5.110678,3.451134,...,0.398327,0.434734,0.424986,-0.008191,0.150125,-0.134563,0.492610,-0.275339,0.029132,0.147880
4,1.164939,-3.816804,-2.957736,7.048094,-1.506204,-0.282389,-11.105441,-2.808455,6.619218,1.091929,...,0.269098,0.140016,-0.219477,-0.052143,-0.015495,0.330496,0.558587,-0.240852,0.035034,-0.846394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
152,4.080963,-6.359069,-5.269644,11.860126,-0.075333,3.266928,-18.994394,-1.355099,14.285904,4.428610,...,-0.180873,-0.124348,-0.549422,0.079085,0.075019,0.445874,0.769192,0.268825,0.107943,-0.835486
153,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
154,3.543678,-4.939993,-2.745279,5.001237,3.252913,2.434391,-12.037653,-4.270888,5.143949,-0.947130,...,0.178954,-0.141457,-0.531013,-0.017829,-0.111482,0.153350,0.249961,-0.323089,0.162780,-0.450837
155,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(156, 5374)

(156, 3719)

(156, 2382)

(493, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
4,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
488,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
489,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
490,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
491,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
492,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(493, 5374)

(493, 3724)

(493, 2386)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
3,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
4,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
151,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
152,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
153,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3724)

(155, 2386)

(159, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,3.259504,-6.948333,-5.314281,16.877680,-1.561594,1.677068,-21.192827,-1.086085,15.852525,7.113788,...,0.054741,0.168013,-0.505847,0.202824,0.007140,0.245082,0.770282,0.036515,0.059159,-1.034368
1,1.946976,-2.980429,-2.636499,7.289874,1.628015,-0.297279,-11.122530,-1.336751,6.379766,1.658195,...,0.335199,0.413946,-0.333739,0.184091,-0.081183,-0.326471,0.074902,-0.338936,0.017037,-0.423300
2,1.331712,-3.429876,-2.917234,9.412067,-0.096169,-0.064359,-13.828246,-1.243533,9.702394,3.003018,...,0.680291,-0.399387,0.066852,0.019135,-0.004352,-0.077583,1.282859,-0.437072,0.713512,-1.019335
3,1.566341,-5.354629,-5.386654,9.835262,-0.384669,-3.275514,-14.374892,-1.059469,12.336576,4.723774,...,0.183878,0.090865,-0.231083,-0.203937,-0.023517,0.132470,0.948315,-0.398109,-0.005508,-0.844747
4,2.791644,-2.384639,-3.168244,6.733860,7.864365,0.821193,-17.236683,-5.050505,6.819553,-0.689976,...,0.055044,0.085949,-0.373811,-0.021753,-0.238453,0.180251,0.349273,-0.244833,-0.122203,-0.272942
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,2.875931,-3.222089,-5.788570,7.097994,0.962627,1.479316,-10.616526,-2.792910,4.344872,0.544410,...,0.142886,-0.102570,0.170256,-0.133289,-0.142881,-0.621665,1.105325,-0.584412,0.735228,-0.429748
155,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
156,4.080963,-6.359069,-5.269644,11.860126,-0.075333,3.266928,-18.994394,-1.355099,14.285904,4.428610,...,-0.180873,-0.124348,-0.549422,0.079085,0.075019,0.445874,0.769192,0.268825,0.107943,-0.835486
157,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
158,3.543678,-4.939993,-2.745279,5.001237,3.252913,2.434391,-12.037653,-4.270888,5.143949,-0.947130,...,0.178954,-0.141457,-0.531013,-0.017829,-0.111482,0.153350,0.249961,-0.323089,0.162780,-0.450837

(159, 5374)

(159, 3724)

(159, 2386)

(491, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
2,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
3,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
4,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
486,3.387227,-3.312556,-3.568770,9.836091,-2.975115,-4.776808,-15.644789,0.402767,11.404202,5.728592,...,0.259191,-0.156011,-0.657177,0.090683,-0.131137,-0.044086,0.658195,-0.148066,-0.333033,-0.870234
487,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
488,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
489,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
490,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533

(491, 5374)

(491, 3691)

(491, 2364)

(155, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
1,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
2,3.122352,-4.797743,-4.334104,8.883557,-1.110481,1.572075,-12.491373,-1.006147,6.489933,1.562312,...,0.105951,0.025249,-0.059851,0.195589,0.053872,-0.013458,0.434167,-0.095912,0.032065,-0.632685
3,3.421278,-4.980500,-1.818619,4.949851,2.646937,-0.494111,-14.675534,1.573397,9.757618,1.263535,...,-0.307539,0.245799,-0.106744,-0.264735,0.080338,0.211269,1.132695,-0.222763,-0.061978,-0.806557
4,3.650284,-1.422407,-3.521151,7.320927,-1.333769,2.509427,-8.297083,1.643375,5.793886,5.512853,...,-0.077185,0.191360,-0.504341,-0.058500,-0.128520,0.108197,0.814795,-0.230626,-0.438794,-0.017016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
151,1.374511,-0.675140,-2.824939,5.038210,2.033863,-0.082512,-11.515170,-0.055934,7.355017,-0.492074,...,-0.000420,0.137074,-0.281582,-0.294153,0.279158,-0.250988,0.684757,-0.736332,0.065020,-0.067626
152,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
153,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612
154,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(155, 5374)

(155, 3691)

(155, 2364)

(161, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
3,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
4,2.975206,-6.491653,-3.839927,11.821246,-0.138459,1.003587,-17.784031,-2.597596,12.989882,3.524831,...,0.155326,0.251512,-0.274766,-0.096163,-0.007197,0.296403,0.830893,-0.167375,0.300061,-0.861038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,2.290391,-1.555030,-2.027585,5.427836,2.616212,1.212105,-11.124537,-0.277540,5.989487,-0.544919,...,0.083183,0.174510,-0.304669,-0.249486,0.221935,-0.219294,0.534043,-0.708747,-0.097672,0.005163
157,3.174270,-3.787992,-4.284914,10.486748,-2.209318,0.314947,-11.841339,-0.726137,10.180140,3.709490,...,0.266872,-0.009687,-0.001082,0.119847,0.311209,0.014553,0.495871,-0.220561,0.080125,-0.764630
158,3.431850,-3.951498,-3.873784,11.321042,-1.470229,-0.033905,-12.651198,-0.759370,9.544827,2.745059,...,0.332333,-0.200369,0.149653,0.110235,0.264349,-0.007880,0.597121,-0.437636,0.532644,-0.581497
159,3.543678,-4.939993,-2.745279,5.001237,3.252913,2.434391,-12.037653,-4.270888,5.143949,-0.947130,...,0.178954,-0.141457,-0.531013,-0.017829,-0.111482,0.153350,0.249961,-0.323089,0.162780,-0.450837
160,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(161, 5374)

(161, 3691)

(161, 2364)

(489, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,5.744293,-7.785055,-3.891767,11.262932,0.251325,0.310802,-16.780500,-1.574069,10.337992,5.297069,...,-0.086957,0.134045,0.056459,-0.335765,0.136977,0.272289,1.180151,-0.274104,0.327263,-0.534128
1,3.740307,-6.143758,-2.042488,10.055068,-1.950604,2.415757,-14.389182,-1.108633,10.755788,3.516679,...,-0.014316,0.385896,-0.545804,0.038958,0.287735,0.626203,1.166353,-0.095385,-0.005796,-0.972924
2,1.892995,-2.910985,-5.066493,6.719724,2.717901,-0.662510,-15.660507,-1.218678,14.743545,6.036386,...,0.086489,0.322726,-0.310237,-0.213189,0.255174,-0.006288,0.675269,-0.309778,0.443007,-0.872722
3,5.114468,-4.830433,-5.447062,10.757203,0.077670,0.495645,-12.574245,-2.077898,7.660981,3.149048,...,-0.250937,0.206534,-0.223312,0.343322,-0.241193,0.214450,1.021452,-0.288710,-0.215809,-0.786897
4,2.010692,-1.409427,-3.583793,3.778501,1.039966,-1.023768,-7.496891,-0.705993,5.007909,2.194638,...,0.054637,0.027199,-0.383653,0.068650,0.585950,-0.025223,0.926432,0.213663,-0.226463,-0.451652
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
484,2.365839,-5.633009,-3.388613,10.866866,-1.929445,0.710701,-15.617691,-1.977192,10.801051,3.905593,...,0.279238,0.092157,-0.210265,-0.054687,0.159311,0.148841,1.103577,-0.306556,0.361056,-0.596046
485,2.876224,-5.038481,-3.354145,4.159993,0.195354,-1.229711,-6.549203,0.585766,1.457568,0.045052,...,-0.088278,0.292331,-0.240328,-0.308141,-0.375836,-0.005479,0.483670,-0.645472,0.012842,-0.240922
486,3.581094,-6.064793,-2.769171,6.592866,-0.030812,-0.284410,-9.875506,0.379415,4.067562,0.976918,...,0.253126,0.356655,-0.030671,-0.108964,0.162669,0.056533,0.501798,-0.532637,-0.328418,-0.128803
487,6.006550,-3.192772,-1.598197,8.621552,1.161149,1.036497,-16.526041,-1.208678,8.910546,2.469460,...,-0.044411,0.187768,-0.620578,0.031293,0.052853,0.135566,0.778522,-0.409223,0.325615,-0.688533
488,3.211861,-0.927248,-2.503729,6.016159,0.937414,0.938717,-8.829222,-0.142341,5.627768,2.525043,...,0.060296,0.059718,-0.516339,-0.078960,0.372638,-0.117332,0.660407,-0.602882,0.343016,-0.861657

(489, 5374)

(489, 3797)

(489, 2436)

(156, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,6.052453,-2.925424,-2.070877,8.495329,1.301863,1.117611,-16.032846,-1.642392,9.346370,2.927347,...,0.051274,0.277398,-0.593216,0.042848,-0.011813,0.098258,0.729520,-0.701225,0.259042,-0.592370
1,4.284906,-4.222572,-3.638047,6.127689,2.785984,-0.247923,-15.491641,0.266604,11.284584,2.270757,...,-0.160620,0.230485,-0.263681,-0.565322,0.152238,0.453253,1.078272,-0.581477,-0.351562,-0.548172
2,2.931786,-4.380294,-4.727276,12.547298,-0.920773,0.859071,-14.014235,-1.219353,10.044724,4.105293,...,0.153847,0.328493,0.075381,0.357536,-0.166716,0.382348,1.111882,-0.605728,0.704239,-0.395475
3,1.743730,-3.338871,-3.909232,9.079329,-0.037647,1.761282,-9.273742,-1.840290,6.192113,2.700553,...,0.035823,0.167362,-0.433423,0.205981,-0.010362,0.084226,0.835776,-0.102376,0.034455,-0.529700
4,3.250073,-3.554803,-2.132563,5.592683,-1.939698,-0.764838,-11.769052,0.243908,7.156982,6.107278,...,0.346624,0.561929,0.005611,-0.529639,-0.168346,-0.015580,1.096539,-0.526291,0.313751,-0.064641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2.692412,-2.698298,-3.099076,5.924388,2.515148,1.043248,-14.169887,-1.128114,7.135630,0.069799,...,-0.204784,0.344236,-0.037872,0.056221,-0.041903,0.327363,0.842283,-0.558174,0.298023,-0.511920
152,3.475780,-4.380733,-2.758807,9.353759,1.040765,0.409037,-11.019807,-0.323877,6.750553,2.186344,...,0.078499,0.469556,-0.532617,0.132853,0.270577,-0.125446,0.907505,-0.135723,-0.105676,-0.572053
153,0.753782,-4.528024,-2.903220,10.845802,-0.331633,2.269931,-12.580269,-0.546933,7.812548,1.241675,...,0.269739,0.078071,-0.294383,0.728949,-0.457967,0.072138,0.377833,-0.547883,-0.014865,-0.573838
154,2.773490,-4.010191,-3.766330,6.389736,-1.026446,-1.372350,-11.063708,-0.433576,6.872968,2.686908,...,0.185444,0.067330,-0.201065,-0.469250,0.165926,0.084891,0.874900,-0.314675,-0.062703,-0.665469
155,1.695650,-4.519942,-4.081422,9.040586,-0.550166,-1.029807,-14.661862,-1.882285,12.320095,4.262482,...,0.158011,0.179584,-0.359837,-0.009297,-0.002829,0.065308,0.727929,-0.474106,0.115676,-0.461612

(156, 5374)

(156, 3797)

(156, 2436)

(162, 4306)

pandas.core.frame.DataFrame

Some weights of RobertaModel were not initialized from the model checkpoint at entropy/roberta_zinc_480m and are newly initialized: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

pandas.core.frame.DataFrame

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,2.516871,0.534238,-2.452955,7.686741,0.431078,-0.694065,-12.601948,-0.971291,7.476032,3.846928,...,-0.143628,0.515095,-0.074862,-0.102673,0.103030,0.130476,0.499113,-0.214322,-0.077564,-0.431823
1,4.884953,-7.157942,-5.138814,13.006714,-2.730479,0.151554,-20.335842,-2.198932,17.312227,6.219527,...,0.010942,0.226891,-0.549037,0.132376,0.037968,0.605839,0.911198,-0.137456,0.129961,-0.967576
2,2.763307,-3.071845,-4.337036,7.157831,1.675385,-0.164037,-14.796813,0.702609,8.210071,3.552740,...,0.043420,0.275199,-0.554195,-0.329015,-0.197298,0.412721,0.569449,-0.312527,-0.098183,-0.531841
3,5.317841,-3.904930,-5.222112,10.552648,-0.299198,0.792047,-13.066146,-1.410062,9.210221,4.334833,...,-0.297946,0.241099,-0.360677,0.370727,-0.181313,0.198411,1.087878,-0.556719,-0.322968,-0.667929
4,2.975206,-6.491653,-3.839927,11.821246,-0.138459,1.003587,-17.784031,-2.597596,12.989882,3.524831,...,0.155326,0.251512,-0.274766,-0.096163,-0.007197,0.296403,0.830893,-0.167375,0.300061,-0.861038
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,4.732400,-5.931112,-2.695037,7.379294,0.355767,1.439902,-9.418824,-0.047803,4.838798,0.808847,...,0.349798,0.256530,-0.020947,-0.335571,-0.034310,0.108234,0.765672,-0.501721,-0.253853,-0.082646
158,2.183160,-2.231052,-2.962017,7.712423,-0.278175,0.161704,-8.929571,-0.744787,6.846818,2.309243,...,-0.268816,0.230295,-0.299570,0.210466,0.212637,-0.155051,0.824359,-0.204696,0.053603,-0.599155
159,4.080963,-6.359069,-5.269644,11.860126,-0.075333,3.266928,-18.994394,-1.355099,14.285904,4.428610,...,-0.180873,-0.124348,-0.549422,0.079085,0.075019,0.445874,0.769192,0.268825,0.107943,-0.835486
160,1.697251,-2.229853,-2.875325,7.633800,-0.657874,-0.268612,-8.608117,-0.441910,7.232983,2.815516,...,-0.106652,0.258743,-0.016806,-0.088005,0.264663,-0.236336,0.674913,-0.257922,0.189105,-0.678619
161,3.555410,-4.378922,-3.521378,6.625486,0.738876,-0.233444,-13.037959,-1.602123,7.619553,0.304590,...,-0.140746,0.202888,-0.370624,-0.340447,0.601488,-0.022932,1.021829,-0.064751,-0.166953,-0.500140

(162, 5374)

(162, 3797)

(162, 2436)

In [129]:
X1_all.X

,300,301,302,303,304,305,306,307,308,309,...,RDkit_fr_piperzine,RDkit_fr_pyridine,RDkit_fr_sulfide,RDkit_fr_sulfonamd,RDkit_fr_sulfone,RDkit_fr_thiazole,RDkit_fr_thiophene,RDkit_fr_unbrch_alkane,RDkit_fr_urea,RDkit_qed
QSPRID,,,,,,,,,,,,,,,,,,,,,
CK1Dataset_000,-0.183866,0.578967,0.161637,0.422820,-0.359473,-1.000239,0.778588,0.269597,0.671282,0.095040,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.389416
CK1Dataset_001,-0.526914,0.482046,0.214669,0.376727,-0.234737,-0.584075,0.579262,-0.091283,0.320457,-0.131275,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.351908
CK1Dataset_002,-0.527138,0.293057,0.296170,0.215663,-0.075322,-1.196916,0.347968,0.003652,0.324451,0.011451,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.312720
CK1Dataset_003,-0.255575,0.203898,0.418056,0.378673,-0.129638,-0.148893,0.742217,-0.251707,-0.097038,0.531059,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.441687
CK1Dataset_004,-0.687007,0.620376,0.137707,-0.190699,0.417505,-0.457825,0.332847,-0.721059,-0.052884,-0.030075,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.804595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CK1Dataset_484,-0.223748,0.351416,-0.098620,0.191478,0.223344,-0.828098,0.288138,-0.034601,0.138777,0.187323,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.451445
CK1Dataset_485,0.170707,0.057631,0.364865,0.143474,0.144775,0.001812,0.526527,-0.131677,0.087674,0.613961,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.743722
CK1Dataset_486,-0.444729,0.174482,0.096636,0.235764,-0.291311,-0.709107,0.599303,-0.166667,0.334144,0.440379,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.634594
CK1Dataset_487,-0.553960,0.309325,-0.072334,0.550220,0.085403,-0.738842,0.462641,-0.245345,0.130169,0.191991,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.486247
CK1Dataset_488,-0.107170,0.599911,0.221533,0.189897,0.336217,-0.835315,0.387175,-0.708570,-0.145131,-0.222876,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.746762

In [18]:
smiles1 = X1_all.getDF()["SMILES"]

In [36]:
smiles1 = pd.concat([X1_all.getDF()["SMILES"], X2_all.getDF()["SMILES"], X3_all.getDF()["SMILES"]]).reset_index()

In [62]:
X1_all2 = load_datasets("CK1/data/ck1_train_2")

X2_all2 = load_datasets("CK1/data/ck1_val_2")

X3_all2 = load_datasets("CK1/data/ck1_test_2")
smiles2 = pd.concat([X1_all2.getDF()["Drug"], X2_all2.getDF()["Drug"], X3_all2.getDF()["Drug"]]).reset_index()

In [53]:
smiles1[:X1_all.getDF().shape[0]]
smiles1[X1_all.getDF().shape[0]:-X3_all.getDF().shape[0]]
smiles1[-X3_all.getDF().shape[0]:]

     index                                             SMILES
488      0  COc1cc(C)c(NC(=O)CN(C)C)cc1Nc1nc(Nc2cccc(F)c2C...
489      1  CC(C)(C)c1cc(NC(=O)C(=O)c2cccc3ccccc23)n(-c2cc...
490      2            Nc1nnc(-c2cc3c(Oc4ccc(Cl)cc4)cncc3s2)o1
491      3  OCc1ccc(-c2nc(-c3ccccn3)c(-c3ccc4c(c3)OCO4)[nH...
492      4  CS(=O)(=O)CCNCc1ccoc1-c1ccc2ncnc(Nc3ccc(OCc4cc...
..     ...                                                ...
638    150       COc1cc2nc3nc(-c4cccs4)c(-c4cccs4)nc3nc2cc1OC
639    151   NC1(C(=O)NCc2ccc(Cl)cc2)CCN(c2ncnc3[nH]ccc23)CC1
640    152  CCc1cccc(NC(=O)Nc2ccc(Oc3ccc4nc(NC(=O)OC)[nH]c...
641    153  CC(C)CCN1c2nc(Nc3cc(F)c(O)c(F)c3)ncc2N(C)C(=O)C1C
642    154            CC(C)(C)n1nc(-c2ccc(Cl)cc2)c2c(N)ncnc21

[155 rows x 2 columns]

In [125]:
smiles1["SMILES"]
X_all = pd.concat([X1_all.X, X2_all.X, X3_all.X])
y_all =  pd.concat([X1_all.y, X2_all.y, X3_all.y])
for i in range(2, 11):
    X1_all2 = load_datasets(f"CK1/data/ck1_train_{i}")
    X2_all2 = load_datasets(f"CK1/data/ck1_val_{i}")
    X3_all2 = load_datasets(f"CK1/data/ck1_test_{i}")
    smiles2 = pd.concat([X1_all2.getDF()["Drug"], X2_all2.getDF()["Drug"], X3_all2.getDF()["Drug"]]).reset_index()
    indices_map = [list(smiles1["SMILES"]).index(element) for element in smiles2["Drug"]]
    #display(y_all.iloc[indices_map].Y)
    #display(pd.concat([X1_all2.y, X2_all2.y, X3_all2.y]).Y)
    if np.array_equal(y_all.iloc[indices_map].Y, pd.concat([X1_all2.y, X2_all2.y, X3_all2.y]).Y):
        print("good")
    else: 
        print("Critical error")
        break
    X_res = X_all.iloc[indices_map]
    X1_res = X_res.iloc[:X1_all2.getDF().shape[0]]
    X2_res = X_res.iloc[X1_all2.getDF().shape[0]:-X3_all2.getDF().shape[0]]
    X3_res = X_res.iloc[-X3_all2.getDF().shape[0]:]
    X1_res.to_csv(f"CK1/mod_data/X1.{i}")
    X2_res.to_csv(f"CK1/mod_data/X2.{i}")
    X3_res.to_csv(f"CK1/mod_data/X3.{i}")
    X1_all2.y.to_csv(f"CK1/mod_data/y1.{i}")
    X2_all2.y.to_csv(f"CK1/mod_data/y2.{i}")
    X3_all2.y.to_csv(f"CK1/mod_data/y3.{i}")

good
good
good
good
good
good
good
good
good

In [ ]:
smiles2 = pd.concat([X1_all2.getDF()["Drug"], X2_all2.getDF()["Drug"], X3_all2.getDF()["Drug"]]).reset_index()
indices_map = [list(smiles1["SMILES"]).index(element) for element in smiles2["Drug"]]
print(indices_map)

In [87]:
smiles2.iloc[3]

QSPRID                                      A2ARDataset_003
Drug      CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5ccc...
Name: 3, dtype: object

In [88]:
smiles1.iloc[643]

index                                                     0
SMILES    CS(=O)(=O)CCNCc1ccc(-c2ccc3ncnc(Nc4ccc(OCc5ccc...
Name: 643, dtype: object

In [98]:

X_all = pd.concat([X1_all.X, X2_all.X, X3_all.X])
type(X_all.iloc[indices_map]

,300,301,302,303,304,305,306,307,308,309,...,RDkit_fr_piperdine,RDkit_fr_piperzine,RDkit_fr_pyridine,RDkit_fr_sulfide,RDkit_fr_sulfonamd,RDkit_fr_sulfone,RDkit_fr_thiazole,RDkit_fr_thiophene,RDkit_fr_unbrch_alkane,RDkit_qed
QSPRID,,,,,,,,,,,,,,,,,,,,,
A2ARDataset_000,-0.442472,0.207853,0.391181,0.222411,-0.084914,-0.652523,0.186761,-0.141471,-0.138574,0.327026,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.690353
A2ARDataset_001,-0.547015,0.326527,-0.055402,0.498394,0.059913,-0.783032,0.457208,-0.362948,0.182183,0.154815,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.488490
A2ARDataset_002,-0.183866,0.578967,0.161637,0.422820,-0.359473,-1.000239,0.778588,0.269597,0.671282,0.095040,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.389416
A2ARDataset_000,-0.441387,0.505895,0.160751,0.364176,-0.213932,-0.924353,0.151645,0.289251,0.624456,0.070934,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.169669
A2ARDataset_000,-0.388080,0.826816,0.427821,0.598129,-0.328920,-1.083285,0.688639,0.246900,0.361368,0.369830,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.231465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A2ARDataset_159,-0.577175,0.608860,0.091210,0.595915,0.356120,-0.719083,0.237224,-0.085256,-0.044304,0.147913,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.743948
A2ARDataset_468,-0.773678,0.317389,-0.069955,0.312257,-0.031650,-0.482003,0.612659,0.294355,0.184764,0.260350,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.434504
A2ARDataset_160,-0.444222,0.136241,0.316228,0.284731,-0.208043,-0.829347,0.444270,-0.389058,0.234052,0.321042,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.625114
A2ARDataset_473,-1.047005,0.269953,0.386140,0.457658,-0.314538,-0.735755,0.884397,0.103523,0.385289,0.436846,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.482471
A2ARDataset_153,-0.977625,0.730990,0.396942,0.117182,-0.511990,-1.246781,0.201596,-0.234081,-0.179592,0.370427,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.760423

In [116]:
y_all =  pd.concat([X1_all.y, X2_all.y, X3_all.y])
type(y_all.Y)

pandas.core.series.Series