In [7]:
!pip install qsprpred

Collecting qsprpred
  Using cached qsprpred-3.2.1-py3-none-any.whl.metadata (10 kB)
Collecting parameterized (from qsprpred)
  Using cached parameterized-0.9.0-py2.py3-none-any.whl.metadata (18 kB)
Collecting pebble (from qsprpred)
  Using cached pebble-5.1.1-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: numpy in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from qsprpred) (2.0.1)
Collecting scikit-learn>=1.0.2 (from qsprpred)
  Downloading scikit_learn-1.6.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting pandas>=1.2.2 (from qsprpred)
  Downloading pandas-2.2.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
Collecting matplotlib>=2.0 (from qsprpred)
  Downloading matplotlib-3.10.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting chembl-structure-pipeline>=1.2.0 (from qsprpred)
  Using cached chembl_structure_pipeline-1.2.2-py3-none-any.whl.metadata (3.9 kB)
Collecting rdkit (from qsprpred)
  Downloading rdkit-2024.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting optuna (from qsprpred)
  Using cached optuna-4.2.1-py3-none-any.whl.metadata (17 kB)
Collecting gitpython (from qsprpred)
  Using cached GitPython-3.1.44-py3-none-any.whl.metadata (13 kB)
Collecting xgboost (from qsprpred)
  Using cached xgboost-3.0.0-py3-none-manylinux2014_x86_64.whl.metadata (2.0 kB)
Collecting boruta (from qsprpred)
  Using cached Boruta-0.4.3-py3-none-any.whl.metadata (8.8 kB)
Collecting tqdm (from qsprpred)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting ml2json (from qsprpred)
  Using cached ml2json-0.4.0-py3-none-any.whl.metadata (44 kB)
Collecting jsonpickle (from qsprpred)
  Using cached jsonpickle-4.0.2-py3-none-any.whl.metadata (8.2 kB)
Collecting papyrus-scripts (from qsprpred)
  Using cached papyrus_scripts-2.1.1-py3-none-any.whl.metadata (11 kB)
Collecting gbmtsplits (from qsprpred)
  Using cached gbmtsplits-0.0.8-py3-none-any.whl.metadata (45 kB)
Collecting mlchemad (from qsprpred)
  Using cached mlchemad-1.5.2-py3-none-any.whl.metadata (3.0 kB)
Collecting mols2grid (from qsprpred)
  Using cached mols2grid-2.0.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: setuptools>=46.4.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from chembl-structure-pipeline>=1.2.0->qsprpred) (75.8.0)
Collecting contourpy>=1.0.1 (from matplotlib>=2.0->qsprpred)
  Downloading contourpy-1.3.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.4 kB)
Collecting cycler>=0.10 (from matplotlib>=2.0->qsprpred)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib>=2.0->qsprpred)
  Downloading fonttools-4.56.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (101 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib>=2.0->qsprpred)
  Downloading kiwisolver-1.4.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.2 kB)
Requirement already satisfied: packaging>=20.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from matplotlib>=2.0->qsprpred) (24.2)
Collecting pillow>=8 (from matplotlib>=2.0->qsprpred)
  Downloading pillow-11.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.1 kB)
Collecting pyparsing>=2.3.1 (from matplotlib>=2.0->qsprpred)
  Using cached pyparsing-3.2.2-py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: python-dateutil>=2.7 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from matplotlib>=2.0->qsprpred) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from pandas>=1.2.2->qsprpred) (2025.1)
Collecting tzdata>=2022.7 (from pandas>=1.2.2->qsprpred)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting scipy>=1.6.0 (from scikit-learn>=1.0.2->qsprpred)
  Downloading scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting joblib>=1.2.0 (from scikit-learn>=1.0.2->qsprpred)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn>=1.0.2->qsprpred)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Collecting seaborn (from gbmtsplits->qsprpred)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting pulp (from gbmtsplits->qsprpred)
  Using cached pulp-3.1.1-py3-none-any.whl.metadata (1.3 kB)
Collecting gitdb<5,>=4.0.1 (from gitpython->qsprpred)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting scikit-learn>=1.0.2 (from qsprpred)
  Downloading scikit_learn-1.4.0-1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting numpy (from qsprpred)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting ipywidgets<8,>=7 (from mols2grid->qsprpred)
  Using cached ipywidgets-7.8.5-py2.py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: jinja2>=2.11.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from mols2grid->qsprpred) (3.1.6)
Collecting alembic>=1.5.0 (from optuna->qsprpred)
  Using cached alembic-1.15.1-py3-none-any.whl.metadata (7.2 kB)
Collecting colorlog (from optuna->qsprpred)
  Using cached colorlog-6.9.0-py3-none-any.whl.metadata (10 kB)
Collecting sqlalchemy>=1.4.2 (from optuna->qsprpred)
  Downloading sqlalchemy-2.0.39-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: PyYAML in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from optuna->qsprpred) (6.0.2)
Requirement already satisfied: requests in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from papyrus-scripts->qsprpred) (2.32.3)
Collecting mordred (from papyrus-scripts->qsprpred)
  Using cached mordred-1.2.0.tar.gz (128 kB)
  Preparing metadata (setup.py) ... done
Collecting swifter (from papyrus-scripts->qsprpred)
  Using cached swifter-1.4.0.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting pystow (from papyrus-scripts->qsprpred)
  Using cached pystow-0.7.0-py3-none-any.whl.metadata (17 kB)
Collecting prodec (from papyrus-scripts->qsprpred)
  Using cached prodec-1.0.2.post5-py3-none-any.whl.metadata (7.0 kB)
Collecting Mako (from alembic>=1.5.0->optuna->qsprpred)
  Using cached Mako-1.3.9-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: typing-extensions>=4.12 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from alembic>=1.5.0->optuna->qsprpred) (4.12.2)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->qsprpred)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: comm>=0.1.3 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipywidgets<8,>=7->mols2grid->qsprpred) (0.2.2)
Collecting ipython-genutils~=0.2.0 (from ipywidgets<8,>=7->mols2grid->qsprpred)
  Using cached ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: traitlets>=4.3.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipywidgets<8,>=7->mols2grid->qsprpred) (5.14.3)
Collecting widgetsnbextension~=3.6.10 (from ipywidgets<8,>=7->mols2grid->qsprpred)
  Using cached widgetsnbextension-3.6.10-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: ipython>=4.0.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipywidgets<8,>=7->mols2grid->qsprpred) (9.0.2)
Collecting jupyterlab-widgets<3,>=1.0.0 (from ipywidgets<8,>=7->mols2grid->qsprpred)
  Using cached jupyterlab_widgets-1.1.11-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jinja2>=2.11.0->mols2grid->qsprpred) (3.0.2)
Requirement already satisfied: six>=1.5 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib>=2.0->qsprpred) (1.17.0)
Collecting greenlet!=0.4.17 (from sqlalchemy>=1.4.2->optuna->qsprpred)
  Downloading greenlet-3.1.1-cp311-cp311-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Collecting networkx==2.* (from mordred->papyrus-scripts->qsprpred)
  Using cached networkx-2.8.8-py3-none-any.whl.metadata (5.1 kB)
Collecting orjson (from prodec->papyrus-scripts->qsprpred)
  Downloading orjson-3.10.16-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Requirement already satisfied: psutil in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from prodec->papyrus-scripts->qsprpred) (5.9.0)
Collecting click (from pystow->papyrus-scripts->qsprpred)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from requests->papyrus-scripts->qsprpred) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from requests->papyrus-scripts->qsprpred) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from requests->papyrus-scripts->qsprpred) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from requests->papyrus-scripts->qsprpred) (2025.1.31)
Collecting dask>=2.10.0 (from dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Using cached dask-2025.3.0-py3-none-any.whl.metadata (3.8 kB)
Collecting cloudpickle>=3.0.0 (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Using cached cloudpickle-3.1.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: fsspec>=2021.09.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred) (2024.12.0)
Collecting partd>=1.4.0 (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Using cached partd-1.4.2-py3-none-any.whl.metadata (4.6 kB)
Collecting toolz>=0.10.0 (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Using cached toolz-1.0.0-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: importlib_metadata>=4.13.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred) (8.6.1)
Collecting pyarrow>=14.0.1 (from dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Downloading pyarrow-19.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: decorator in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.19.2)
Requirement already satisfied: matplotlib-inline in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (2.19.1)
Requirement already satisfied: stack_data in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.6.3)
Requirement already satisfied: notebook>=4.4.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (7.3.3)
Requirement already satisfied: zipp>=3.20 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from importlib_metadata>=4.13.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred) (3.21.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jedi>=0.16->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.8.4)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (2.27.3)
Requirement already satisfied: jupyterlab<4.4,>=4.3.6 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (4.3.6)
Requirement already satisfied: notebook-shim<0.3,>=0.2 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.2.4)
Requirement already satisfied: tornado>=6.2.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (6.4.2)
Collecting locket (from partd>=1.4.0->dask>=2.10.0->dask[dataframe]>=2.10.0->swifter->papyrus-scripts->qsprpred)
  Using cached locket-1.0.0-py2.py3-none-any.whl.metadata (2.8 kB)
Requirement already satisfied: ptyprocess>=0.5 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from pexpect>4.3->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.7.0)
Requirement already satisfied: wcwidth in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.2.13)
Requirement already satisfied: executing>=1.2.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from stack_data->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (2.1.0)
Requirement already satisfied: asttokens>=2.1.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from stack_data->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (3.0.0)
Requirement already satisfied: pure_eval in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from stack_data->ipython>=4.0.0->ipywidgets<8,>=7->mols2grid->qsprpred) (0.2.3)
Requirement already satisfied: anyio>=3.1.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (4.9.0)
Requirement already satisfied: argon2-cffi>=21.1 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (23.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (5.7.2)
Requirement already satisfied: jupyter-events>=0.11.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (5.10.4)
Requirement already satisfied: overrides>=5.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (7.7.0)
Requirement already satisfied: prometheus-client>=0.9 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.21.1)
Requirement already satisfied: pyzmq>=24 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (26.2.0)
Requirement already satisfied: send2trash>=1.8.2 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyter-server<3,>=2.4.0->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (1.8.0)
Requirement already satisfied: async-lru>=1.0.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyterlab<4.4,>=4.3.6->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (2.0.5)
Requirement already satisfied: httpx>=0.25.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyterlab<4.4,>=4.3.6->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (0.28.1)
Requirement already satisfied: ipykernel>=6.5.0 in /home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages (from jupyterlab<4.4,>=4.3.6->notebook>=4.4.1->widgetsnbextension~=3.6.10->ipywidgets<8,>=7->mols2grid->qsprpred) (6.29.5)

/home/ubuntu/miniconda3/lib/python3.12/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [3]:

import os
import qsprpred

from qsprpred.extra.gpu.models.neural_network import STFullyConnected

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP

os.makedirs("tutorial_output_test/data", exist_ok=True)

# Create dataset
dataset = QSPRDataset.fromTableFile(
    filename="../../../../tutorials/tutorial_data/A2A_LIGANDS.tsv",
    store_dir="tutorial_output_test/data",
    name="MonitoringTutorialDataset",
    target_props=[{"name": "pchembl_value_Mean", "task": "SINGLECLASS", "th": [6.5]}],
    random_state=42
)

/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(

In [6]:
display(dataset.df)

,SMILES,pchembl_value_Mean,Year,QSPRID,pchembl_value_Mean_original
QSPRID,,,,,
MonitoringTutorialDataset_0000,Cc1cc(C)n(-c2cc(NC(=O)CCN(C)C)nc(-c3ccc(C)o3)n...,True,2008.0,MonitoringTutorialDataset_0000,8.68
MonitoringTutorialDataset_0001,Nc1c(C(=O)Nc2ccc([N+](=O)[O-])cc2)sc2nc3c(cc12...,False,2010.0,MonitoringTutorialDataset_0001,4.82
MonitoringTutorialDataset_0002,O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1,False,2009.0,MonitoringTutorialDataset_0002,5.65
MonitoringTutorialDataset_0003,CNC(=O)C12CC1C(n1cnc3c(NCc4cccc(Cl)c4)nc(C#CCC...,False,2009.0,MonitoringTutorialDataset_0003,5.45
MonitoringTutorialDataset_0004,CCCn1c(=O)c2c(nc3cc(OC)ccn32)n(CCCNC(=O)c2ccc(...,False,2019.0,MonitoringTutorialDataset_0004,5.20
...,...,...,...,...,...
MonitoringTutorialDataset_4077,CNc1ncc(C(=O)NCc2ccc(OC)cc2)c2nc(-c3ccco3)nn12,True,2018.0,MonitoringTutorialDataset_4077,7.09
MonitoringTutorialDataset_4078,Nc1nc(-c2ccco2)c2ncn(C(=O)NCCc3ccccc3)c2n1,True,2008.0,MonitoringTutorialDataset_4078,8.22
MonitoringTutorialDataset_4079,Nc1nc(CSc2nnc(N)s2)nc(Nc2ccc(F)cc2)n1,False,2010.0,MonitoringTutorialDataset_4079,4.89
MonitoringTutorialDataset_4080,CCCOc1ccc(C=Cc2cc3c(c(=O)n(C)c(=O)n3C)n2C)cc1,True,2013.0,MonitoringTutorialDataset_4080,6.51
MonitoringTutorialDataset_4081,CCOC(=O)c1cnc(NCC(C)C)n2nc(-c3ccco3)nc12,True,2014.0,MonitoringTutorialDataset_4081,7.35

In [7]:
# calculate compound features and split dataset into train and test
dataset.prepareDataset(
    split=RandomSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
)

dataset.getDF().head()

,SMILES,pchembl_value_Mean,Year,QSPRID,pchembl_value_Mean_original
QSPRID,,,,,
MonitoringTutorialDataset_0000,Cc1cc(C)n(-c2cc(NC(=O)CCN(C)C)nc(-c3ccc(C)o3)n...,True,2008.0,MonitoringTutorialDataset_0000,8.68
MonitoringTutorialDataset_0001,Nc1c(C(=O)Nc2ccc([N+](=O)[O-])cc2)sc2nc3c(cc12...,False,2010.0,MonitoringTutorialDataset_0001,4.82
MonitoringTutorialDataset_0002,O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1,False,2009.0,MonitoringTutorialDataset_0002,5.65
MonitoringTutorialDataset_0003,CNC(=O)C12CC1C(n1cnc3c(NCc4cccc(Cl)c4)nc(C#CCC...,False,2009.0,MonitoringTutorialDataset_0003,5.45
MonitoringTutorialDataset_0004,CCCn1c(=O)c2c(nc3cc(OC)ccn32)n(CCCNC(=O)c2ccc(...,False,2019.0,MonitoringTutorialDataset_0004,5.20

In [4]:
display("ahoj")

'ahoj'

In [5]:
display(dataset.X)

,MorganFP_MorganFP_0,MorganFP_MorganFP_1,MorganFP_MorganFP_2,MorganFP_MorganFP_3,MorganFP_MorganFP_4,MorganFP_MorganFP_5,MorganFP_MorganFP_6,MorganFP_MorganFP_7,MorganFP_MorganFP_8,MorganFP_MorganFP_9,...,MorganFP_MorganFP_2038,MorganFP_MorganFP_2039,MorganFP_MorganFP_2040,MorganFP_MorganFP_2041,MorganFP_MorganFP_2042,MorganFP_MorganFP_2043,MorganFP_MorganFP_2044,MorganFP_MorganFP_2045,MorganFP_MorganFP_2046,MorganFP_MorganFP_2047
QSPRID,,,,,,,,,,,,,,,,,,,,,
MonitoringTutorialDataset_0221,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
MonitoringTutorialDataset_3644,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_2459,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1315,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1017,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MonitoringTutorialDataset_1130,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
MonitoringTutorialDataset_1294,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
MonitoringTutorialDataset_0860,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
MonitoringTutorialDataset_3507,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_3174,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:

# Přidejte cestu k vašemu lokálnímu repozitáři
import sys
import os

# Přidání cesty k lokálnímu repozitáři na začátek sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Zkontrolujte, zda je cesta v sys.path
print(sys.path)

['/home/ubuntu/Bakalarka/QSPRpred', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python311.zip', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/lib-dynload', '', '/home/ubuntu/miniconda3/envs/bakalarka_env/lib/python3.11/site-packages']

In [9]:
from importlib import reload

# Znovu načtěte modul, abyste zajistili, že je správně importován
reload(sys.modules['qsprpred.extra.gpu.models.neural_network'])

# Znovu proveďte import
from qsprpred.extra.gpu.models.neural_network import STFullyConnected

In [10]:
os.chdir('/home/ubuntu/Bakalarka/QSPRpred')
print(os.getcwd())

/home/ubuntu/Bakalarka/QSPRpred

In [11]:
import sys
import importlib.util

# Přidání cesty k repozitáři do sys.path
sys.path.insert(0, '/home/ubuntu/Bakalarka/QSPRpred')

# Specifikujte cestu k souboru, který chcete importovat
module_path = '/home/ubuntu/Bakalarka/QSPRpred/qsprpred/extra/gpu/models/neural_network.py'
module_name = 'qsprpred.extra.gpu.models.neural_network'

# Načtěte modul z konkrétní cesty
spec = importlib.util.spec_from_file_location(module_name, module_path)
neural_network = importlib.util.module_from_spec(spec)
spec.loader.exec_module(neural_network)

# Nyní můžete používat třídu STFullyConnected
STFullyConnected = neural_network.STFullyConnected

lol

In [12]:
from torch.nn import functional as F

print("xd")
model_sts = STFullyConnected(
    n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
    n_class=1,  # regresní úloha (1 výstup)
    gpus=[],
    device="cuda",
    batch_size=256,
    patience=100,
    tol=1e-4,
    neuron_layers=[4000, 3000, 1000, 500, 200], #[3000, 1500, 500, 100]
    act_fun=F.selu,
    is_reg=False
)
model_sts.fit(dataset.X, dataset.y)

xd

(STFullyConnected(
   (layers): ModuleList(
     (0): Linear(in_features=2048, out_features=4000, bias=True)
     (1): Linear(in_features=4000, out_features=3000, bias=True)
     (2): Linear(in_features=3000, out_features=1000, bias=True)
     (3): Linear(in_features=1000, out_features=500, bias=True)
     (4): Linear(in_features=500, out_features=200, bias=True)
     (5): Linear(in_features=200, out_features=1, bias=True)
   )
   (dropout): Dropout(p=0.25, inplace=False)
   (criterion): BCELoss()
   (final_layer_activation): Sigmoid()
 ),
 0)

In [32]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score
param_grid = ParameterGrid({
    "act_fun": [F.selu, F.elu, F.gelu, F.silu],
    "dropout_frac": [0, 0.05, 0.1],
    "patience": [100],
    "weight_decay": [1e-4],
    "n_epochs": [200, 350, 500],
    "neuron_layers": [[ 5000, 4096, 2048, 1024], [2048, 1024, 512, 256, 128, 64], [4096, 2048, 1024, 512, 256], [1024, 512, 256, 128, 64, 32, 16]],
})
print(len(param_grid))
i = 0
val_f1 = []
param_len = len(param_grid)
for param in param_grid:
    i += 1
    print(i, '/', param_len)
    model_sts = STFullyConnected(n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
    n_class=1,  # regresní úloha (1 výstup)
    gpus=[],
    device="cuda",
    batch_size=256,is_reg=False, **param)
    model_sts.fit(dataset.X, dataset.y)
    res = model_sts.predict(dataset.X_ind)
    res = res >0.5
    val_f1.append(f1_score(res, dataset.y_ind))
    print(param)
    print(f1_score(res, dataset.y_ind))

144
1 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8408644400785854
2 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8507751937984496
3 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8529411764705882
4 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8389513108614233
5 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8260869565217391
6 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.84251968503937
7 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8272458045409674
8 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8498098859315589
9 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8257425742574257
10 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8305252725470763
11 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8189910979228486
12 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8491834774255523
13 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8431372549019608
14 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8507751937984496
15 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8501469147894222
16 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.839851024208566
17 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8260869565217391
18 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8385826771653543
19 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8272458045409674
20 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8490028490028491
21 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8245787908820614
22 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.83399209486166
23 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8222442899702085
24 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8519230769230769
25 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8428290766208252
26 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8532818532818532
27 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8512720156555773
28 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8372093023255814
29 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8272458045409674
30 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8411764705882353
31 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8265609514370664
32 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8500948766603416
33 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8245787908820614
34 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8374384236453202
35 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8222442899702085
36 / 144
{'act_fun': <function selu at 0x7f1f3be4d580>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8508180943214629
37 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8423114593535749
38 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8472622478386167
39 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8494208494208494
40 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.7962489343563512
41 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8287401574803149
42 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8504854368932039
43 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8298918387413963
44 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8403669724770643
45 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8206144697720515
46 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8473581213307241
47 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8215353938185443
48 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.848314606741573
49 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8406647116324536
50 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8472622478386167
51 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8494208494208494
52 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.7962648556876061
53 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8279252704031466
54 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8516003879728419
55 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8315270935960591
56 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8403669724770643
57 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8206144697720515
58 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8434442270058709
59 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8207171314741036
60 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8475210477081384
61 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8390243902439024
62 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8456375838926175
63 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8502415458937198
64 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.7955894826123834
65 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8287401574803149
66 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8527131782945736
67 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.83399209486166
68 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8403669724770643
69 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8221343873517787
70 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.845703125
71 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8199004975124378
72 / 144
{'act_fun': <function elu at 0x7f1f3be4d4e0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8475210477081384
73 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8541062801932368
74 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.7681498829039812
75 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8437200383509108
76 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.0
77 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8399209486166008
78 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8154589371980676
79 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8513119533527697
80 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.7986906710310966
81 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8305252725470763
82 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8455598455598455
83 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8399209486166008
84 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8134135855546002
85 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8541062801932368
86 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.7681498829039812
87 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8426103646833013
88 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.0
89 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.841897233201581
90 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8166023166023166
91 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8510223953261928
92 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 350, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.7990115321252059
93 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.827037773359841
94 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8444444444444444
95 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8399209486166008
96 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.05, 'n_epochs': 500, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.8130921619293713
97 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8552123552123552
98 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.7681498829039812
99 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8426103646833013
100 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [1024, 512, 256, 128, 64, 32, 16], 'patience': 100, 'weight_decay': 0.0001}
0.0
101 / 144
{'act_fun': <built-in function gelu>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [5000, 4096, 2048, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8402366863905325

In [22]:
from sklearn.metrics import f1_score

# print(model_sts.predict(dataset.X_ind))
res = model_sts.predict(dataset.X_ind)
res = res > 0.5
print(f1_score(dataset.y_ind, res))

0.8505747126436781

In [38]:
import numpy as np


print(param_grid[np.argmax(val_f1)])
print(max(val_f1))

{'weight_decay': 0.0001, 'patience': 100, 'neuron_layers': [5000, 4096, 2048, 1024], 'n_epochs': 200, 'dropout_frac': 0.1, 'act_fun': <built-in function gelu>}
0.8552123552123552

In [14]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score

param_grid_2 = ParameterGrid({
    "act_fun": [F.selu, F.elu, F.silu],
    "dropout_frac": [ 0.1, 0.2, 0.3, 0.4],
    "patience": [100],
    "weight_decay": [1e-4],
    "n_epochs": [1200, 350, 200, 500],
    "neuron_layers": [[ 5000, 1024], [2048, 1024, 512, 256, 128, 64, 32, 16, 8], [4096, 2048, 1024, 512, 256], [2048, 1024, 512, 256, 128, 64], [2048, 512, 512, 512, 126, 32]]
})
print(len(param_grid_2))
i = 0
val_f1_2 = []
param_len_2 = len(param_grid_2)
for param in param_grid_2:
    i += 1
    print(i, '/', param_len_2)
    model_sts_2 = STFullyConnected(n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
    n_class=1,  # regresní úloha (1 výstup)
    gpus=[],
    device="cuda",
    batch_size=256,is_reg=False, **param)
    model_sts_2.fit(dataset.X, dataset.y)
    res = model_sts_2.predict(dataset.X_ind)
    res = res >0.5
    val_f1_2.append(f1_score(res, dataset.y_ind))
    print(param)
    print(f1_score(res, dataset.y_ind))

240
1 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8285431119920713
2 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8316633266533067
3 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8238805970149253
4 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.824
5 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8279252704031466
6 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8524590163934426
7 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8544423440453687
8 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8265609514370664
9 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8411764705882353
10 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.847424684159378
11 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8538681948424068
12 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8483720930232558
13 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8512720156555773
14 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8532818532818532
15 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8513513513513513
16 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.84765625
17 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.848893166506256
18 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8222442899702085
19 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8374384236453202
20 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8414872798434442
21 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 1200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8293650793650794
22 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8371174728529122
23 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 1200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8238805970149253
24 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8223552894211577
25 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 1200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8280632411067194
26 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 350, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8508180943214629
27 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8493408662900188
28 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8288822947576657
29 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8466019417475729
30 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 350, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8491295938104448
31 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8544243577545195
32 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8439519852262235
33 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8499025341130604
34 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8543876567020251
35 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8508180943214629
36 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 500, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8460038986354775
37 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8522072936660269
38 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8218905472636816
39 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8420019627085378
40 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.2, 'n_epochs': 500, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8442703232125367
41 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 1200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8273809523809523
42 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8346303501945526
43 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 1200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8210735586481114
44 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8235294117647058
45 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 1200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8297029702970297
46 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 350, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8530259365994236
47 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8507042253521127
48 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8357915437561455
49 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8516003879728419
50 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 350, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.847424684159378
51 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8533333333333334
52 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8401826484018264
53 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.851063829787234
54 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8549471661863592
55 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8491834774255523
56 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 500, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8482490272373541
57 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8555133079847909
58 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8206144697720515
59 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8453201970443349
60 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.3, 'n_epochs': 500, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8470588235294118
61 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 1200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8273809523809523
62 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8354430379746836
63 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 1200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8218905472636816
64 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8238805970149253
65 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 1200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8311944718657454
66 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 350, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8538461538461538
67 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8439519852262235
68 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8461538461538461
69 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8518877057115198
70 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 350, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8527131782945736
71 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8525214081826832
72 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.797588285960379
73 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8546679499518768
74 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.845933014354067
75 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8408007626310772
76 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 500, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8493683187560739
77 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8509840674789129
78 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8300395256916996
79 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8450980392156863
80 / 240
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.4, 'n_epochs': 500, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8482490272373541
81 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8273809523809523
82 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8318227593152064
83 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8181818181818182
84 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8190854870775348
85 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 1200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8220255653883972
86 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8543876567020251
87 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8430066603235015
88 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.83399209486166
89 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8527131782945736
90 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 350, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8535402521823472
91 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8514285714285714
92 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8315412186379928
93 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8502415458937198
94 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.8456375838926175
95 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 200, 'neuron_layers': [2048, 512, 512, 512, 126, 32], 'patience': 100, 'weight_decay': 0.0001}
0.8408007626310772
96 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8494208494208494
97 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64, 32, 16, 8], 'patience': 100, 'weight_decay': 0.0001}
0.8493683187560739
98 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'patience': 100, 'weight_decay': 0.0001}
0.8199004975124378
99 / 240
{'act_fun': <function elu at 0x7fa7790179c0>, 'dropout_frac': 0.1, 'n_epochs': 500, 'neuron_layers': [2048, 1024, 512, 256, 128, 64], 'patience': 100, 'weight_decay': 0.0001}
0.845703125
100 / 240

In [16]:
import numpy as np
print(param_grid_2[np.argmax(val_f1_2)])
print(max(val_f1_2))

{'weight_decay': 0.0001, 'patience': 100, 'neuron_layers': [4096, 2048, 1024, 512, 256], 'n_epochs': 200, 'dropout_frac': 0.4, 'act_fun': <function elu at 0x7fa7790179c0>}
0.8582449373191899

In [19]:
test_par = {'weight_decay': 0.0001, 'patience': 100, 
            'neuron_layers': [4096, 2048, 1024, 512, 256],
            'n_epochs': 200, 'dropout_frac': 0.41,
            'act_fun': F.elu}
model_sts_3 = STFullyConnected(n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
    n_class=1,  # regresní úloha (1 výstup)
    gpus=[],
    device="cuda",
    batch_size=256,is_reg=False, **test_par)
model_sts_3.fit(dataset.X, dataset.y)
res = model_sts_3.predict(dataset.X_ind)
res = res >0.5
print(f1_score(res, dataset.y_ind))

0.8582449373191899

In [20]:
from sklearn.metrics import accuracy_score
print(accuracy_score(res, dataset.y_ind))

0.8200734394124847

In [33]:
# Create model
from qsprpred.extra.gpu.models.dnn import DNNModel

os.makedirs("tutorial_output_test/models", exist_ok=True)
model = DNNModel(
    base_dir='tutorial_output_test/models',
    name='MonitoringTutorialModel',
    parameters=model_sts.get_params(),
    patience=3,
    tol=0.01,

)

model.initFromDataset(dataset)
print(model.parameters)
model.estimator = model_sts
display(type(model.estimator))
display(model.estimator)

lol
lol
lol
{'act_fun': <function selu at 0x173ed9b20>, 'batch_size': 256, 'device': device(type='cpu'), 'dropout_frac': 0.25, 'gpus': [], 'is_reg': False, 'lr': 1e-05, 'n_class': 1, 'n_dim': 2048, 'n_epochs': 100, 'neuron_layers': [4000, 3000, 1000, 200], 'patience': 100, 'random_seed': 42, 'tol': 0.0001, 'weight_decay': 0}

qsprpred.extra.gpu.models.neural_network.STFullyConnected

STFullyConnected(
  (layers): ModuleList(
    (0): Linear(in_features=2048, out_features=4000, bias=True)
    (1): Linear(in_features=4000, out_features=3000, bias=True)
    (2): Linear(in_features=3000, out_features=1000, bias=True)
    (3): Linear(in_features=1000, out_features=200, bias=True)
    (4): Linear(in_features=200, out_features=1, bias=True)
  )
  (dropout): Dropout(p=0.25, inplace=False)
  (criterion): BCELoss()
  (final_layer_activation): Sigmoid()
)

In [36]:
from sklearn.metrics import accuracy_score
display(accuracy_score(dataset.y_ind, res))

0.8078335373317014

In [21]:
import pandas as pd

In [22]:
df = pd.DataFrame(param_grid_2)
df["F1"] = val_f1_2

In [23]:
display(df)

,act_fun,dropout_frac,n_epochs,neuron_layers,patience,weight_decay,F1
0,<function selu at 0x7fa779017a60>,0.1,1200,"[5000, 1024]",100,0.0001,0.828543
1,<function selu at 0x7fa779017a60>,0.1,1200,"[2048, 1024, 512, 256, 128, 64, 32, 16, 8]",100,0.0001,0.831663
2,<function selu at 0x7fa779017a60>,0.1,1200,"[4096, 2048, 1024, 512, 256]",100,0.0001,0.823881
3,<function selu at 0x7fa779017a60>,0.1,1200,"[2048, 1024, 512, 256, 128, 64]",100,0.0001,0.824000
4,<function selu at 0x7fa779017a60>,0.1,1200,"[2048, 512, 512, 512, 126, 32]",100,0.0001,0.827925
...,...,...,...,...,...,...,...
235,<function silu at 0x7fa779024360>,0.4,500,"[5000, 1024]",100,0.0001,0.854406
236,<function silu at 0x7fa779024360>,0.4,500,"[2048, 1024, 512, 256, 128, 64, 32, 16, 8]",100,0.0001,0.752672
237,<function silu at 0x7fa779024360>,0.4,500,"[4096, 2048, 1024, 512, 256]",100,0.0001,0.843233
238,<function silu at 0x7fa779024360>,0.4,500,"[2048, 1024, 512, 256, 128, 64]",100,0.0001,0.844614
239,<function silu at 0x7fa779024360>,0.4,500,"[2048, 512, 512, 512, 126, 32]",100,0.0001,0.846520

In [34]:
df["neuron_layers"] = df["neuron_layers"].apply(tuple)
display("Mean:")
display(df.groupby("neuron_layers")["F1"].mean())
display("Median:")
display(df.groupby("neuron_layers")["F1"].median())
display("Max:")
display(df.groupby("neuron_layers")["F1"].max())

'Mean:'

neuron_layers
(2048, 512, 512, 512, 126, 32)                0.833392
(2048, 1024, 512, 256, 128, 64)               0.834494
(2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.811511
(4096, 2048, 1024, 512, 256)                  0.836069
(5000, 1024)                                  0.845510
Name: F1, dtype: float64

'Median:'

neuron_layers
(2048, 512, 512, 512, 126, 32)                0.841796
(2048, 1024, 512, 256, 128, 64)               0.841950
(2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.832753
(4096, 2048, 1024, 512, 256)                  0.837856
(5000, 1024)                                  0.850718
Name: F1, dtype: float64

'Max:'

neuron_layers
(2048, 512, 512, 512, 126, 32)                0.854406
(2048, 1024, 512, 256, 128, 64)               0.856593
(2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.855513
(4096, 2048, 1024, 512, 256)                  0.858245
(5000, 1024)                                  0.857418
Name: F1, dtype: float64

In [32]:
display("Mean:")
display(df.groupby("dropout_frac")["F1"].mean())
display("Median:")
display(df.groupby("dropout_frac")["F1"].median())
display("Max:")
display(df.groupby("dropout_frac")["F1"].max())

'Mean:'

dropout_frac
0.1    0.833324
0.2    0.833335
0.3    0.832069
0.4    0.830052
Name: F1, dtype: float64

'Median:'

dropout_frac
0.1    0.840989
0.2    0.841902
0.3    0.840964
0.4    0.840649
Name: F1, dtype: float64

'Max:'

dropout_frac
0.1    0.857143
0.2    0.857418
0.3    0.855513
0.4    0.858245
Name: F1, dtype: float64

In [37]:
df["act_fun"] = df["act_fun"].astype(str)
display("Mean:")
display(df.groupby("act_fun")["F1"].mean())
display("Median:")
display(df.groupby("act_fun")["F1"].median())
display("Max:")
display(df.groupby("act_fun")["F1"].max())

'Mean:'

act_fun
<function elu at 0x7fa7790179c0>     0.837705
<function selu at 0x7fa779017a60>    0.841041
<function silu at 0x7fa779024360>    0.817840
Name: F1, dtype: float64

'Median:'

act_fun
<function elu at 0x7fa7790179c0>     0.840624
<function selu at 0x7fa779017a60>    0.845968
<function silu at 0x7fa779024360>    0.835062
Name: F1, dtype: float64

'Max:'

act_fun
<function elu at 0x7fa7790179c0>     0.858245
<function selu at 0x7fa779017a60>    0.855513
<function silu at 0x7fa779024360>    0.857418
Name: F1, dtype: float64

In [38]:
display("Mean:")
display(df.groupby("n_epochs")["F1"].mean())
display("Median:")
display(df.groupby("n_epochs")["F1"].median())
display("Max:")
display(df.groupby("n_epochs")["F1"].max())

'Mean:'

n_epochs
200     0.827299
350     0.837884
500     0.837290
1200    0.826308
Name: F1, dtype: float64

'Median:'

n_epochs
200     0.843179
350     0.849744
500     0.845209
1200    0.827381
Name: F1, dtype: float64

'Max:'

n_epochs
200     0.858245
350     0.856593
500     0.857418
1200    0.843658
Name: F1, dtype: float64

In [44]:
from sklearn.model_selection import ParameterGrid
from torch.nn import functional as F
from sklearn.metrics import f1_score
import pandas as pd
def test_fun(dic, dataset) -> pd.DataFrame:
    param_grid_t = ParameterGrid(dic)
    i = 0
    val_f1_t = []
    param_len_t = len(param_grid_t)
    for param in param_grid_t:
        i += 1
        print(i, '/', param_len_t)
        model_sts_t = STFullyConnected(n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
        n_class=1,  # regresní úloha (1 výstup)
        gpus=[],
        device="cuda",
        batch_size=256,is_reg=False, **param)
        model_sts_t.fit(dataset.X, dataset.y)
        res = model_sts_t.predict(dataset.X_ind)
        res = res >0.5
        val_f1_t.append(f1_score(res, dataset.y_ind))
        print(param)
        print(f1_score(res, dataset.y_ind))
    my_df = pd.DataFrame(param_grid_t)
    my_df["F1"] = val_f1_t
    return my_df

In [ ]:
my_dict = {
    "act_fun": [F.selu, F.elu,F.gelu],
    "dropout_frac": [ 0.1, 0.25, 0.4, 0.5],
    "patience": [100],
    "weight_decay": [1e-4],
    "n_epochs": [300, 400],
    "neuron_layers": [[ 5000, 1024], [ 8000, 1024],[ 5000, 2500],[ 8000, 2500], [4000], [2000]]
}
df_2 = test_fun(my_dict,dataset)

1 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8538461538461538
2 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [8000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8538461538461538
3 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8505303760848602
4 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [8000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8477206595538312
5 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [4000], 'patience': 100, 'weight_decay': 0.0001}
0.8431001890359168
6 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 300, 'neuron_layers': [2000], 'patience': 100, 'weight_decay': 0.0001}
0.8488262910798122
7 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8527131782945736
8 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [8000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8451801363193768
9 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [5000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8426197458455523
10 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [8000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8428290766208252
11 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [4000], 'patience': 100, 'weight_decay': 0.0001}
0.8528015194681862
12 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.1, 'n_epochs': 400, 'neuron_layers': [2000], 'patience': 100, 'weight_decay': 0.0001}
0.8471698113207548
13 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8519230769230769
14 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [8000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8508180943214629
15 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [5000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8508180943214629
16 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [8000, 2500], 'patience': 100, 'weight_decay': 0.0001}
0.8480154888673765
17 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [4000], 'patience': 100, 'weight_decay': 0.0001}
0.8431001890359168
18 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 300, 'neuron_layers': [2000], 'patience': 100, 'weight_decay': 0.0001}
0.8488262910798122
19 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 400, 'neuron_layers': [5000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8543876567020251
20 / 144
{'act_fun': <function selu at 0x7fa779017a60>, 'dropout_frac': 0.25, 'n_epochs': 400, 'neuron_layers': [8000, 1024], 'patience': 100, 'weight_decay': 0.0001}
0.8454810495626822
21 / 144

In [49]:
display("Mean:")
display(df.groupby(["dropout_frac", "neuron_layers"])["F1"].mean())
display("Median:")
display(df.groupby(["n_epochs", "neuron_layers"])["F1"].median())
display("Max:")
display(df.groupby(["n_epochs", "neuron_layers"])["F1"].max())

'Mean:'

dropout_frac  neuron_layers
0.1           (2048, 512, 512, 512, 126, 32)                0.833929
              (2048, 1024, 512, 256, 128, 64)               0.835059
              (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.817903
              (4096, 2048, 1024, 512, 256)                  0.834095
              (5000, 1024)                                  0.845636
0.2           (2048, 512, 512, 512, 126, 32)                0.834520
              (2048, 1024, 512, 256, 128, 64)               0.834556
              (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.817270
              (4096, 2048, 1024, 512, 256)                  0.834877
              (5000, 1024)                                  0.845455
0.3           (2048, 512, 512, 512, 126, 32)                0.833130
              (2048, 1024, 512, 256, 128, 64)               0.835912
              (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.810521
              (4096, 2048, 1024, 512, 256)                  0.835431
              (5000, 1024)                                  0.845352
0.4           (2048, 512, 512, 512, 126, 32)                0.831989
              (2048, 1024, 512, 256, 128, 64)               0.832451
              (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.800350
              (4096, 2048, 1024, 512, 256)                  0.839874
              (5000, 1024)                                  0.845597
Name: F1, dtype: float64

'Median:'

n_epochs  neuron_layers
200       (2048, 512, 512, 512, 126, 32)                0.839664
          (2048, 1024, 512, 256, 128, 64)               0.843463
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.800138
          (4096, 2048, 1024, 512, 256)                  0.850653
          (5000, 1024)                                  0.851429
350       (2048, 512, 512, 512, 126, 32)                0.848277
          (2048, 1024, 512, 256, 128, 64)               0.848957
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.839051
          (4096, 2048, 1024, 512, 256)                  0.843453
          (5000, 1024)                                  0.853321
500       (2048, 512, 512, 512, 126, 32)                0.842912
          (2048, 1024, 512, 256, 128, 64)               0.846003
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.844701
          (4096, 2048, 1024, 512, 256)                  0.826068
          (5000, 1024)                                  0.849566
1200      (2048, 512, 512, 512, 126, 32)                0.828883
          (2048, 1024, 512, 256, 128, 64)               0.823705
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.831919
          (4096, 2048, 1024, 512, 256)                  0.822300
          (5000, 1024)                                  0.828954
Name: F1, dtype: float64

'Max:'

n_epochs  neuron_layers
200       (2048, 512, 512, 512, 126, 32)                0.851351
          (2048, 1024, 512, 256, 128, 64)               0.854947
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.848372
          (4096, 2048, 1024, 512, 256)                  0.858245
          (5000, 1024)                                  0.854424
350       (2048, 512, 512, 512, 126, 32)                0.854406
          (2048, 1024, 512, 256, 128, 64)               0.856593
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.854442
          (4096, 2048, 1024, 512, 256)                  0.855760
          (5000, 1024)                                  0.855502
500       (2048, 512, 512, 512, 126, 32)                0.848249
          (2048, 1024, 512, 256, 128, 64)               0.848659
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.855513
          (4096, 2048, 1024, 512, 256)                  0.845098
          (5000, 1024)                                  0.857418
1200      (2048, 512, 512, 512, 126, 32)                0.843658
          (2048, 1024, 512, 256, 128, 64)               0.841897
          (2048, 1024, 512, 256, 128, 64, 32, 16, 8)    0.837117
          (4096, 2048, 1024, 512, 256)                  0.827861
          (5000, 1024)                                  0.840237
Name: F1, dtype: float64