In [1]:
import os

from IPython.display import display
from qsprpred.extra.gpu.models.neural_network import STFullyConnected

from qsprpred.data import QSPRDataset, RandomSplit
from qsprpred.data.descriptors.fingerprints import MorganFP

os.makedirs("tutorial_output_test/data", exist_ok=True)

# Create dataset
dataset = QSPRDataset.fromTableFile(
    filename="../../../../tutorials/tutorial_data/A2A_LIGANDS.tsv",
    store_dir="tutorial_output_test/data",
    name="MonitoringTutorialDataset",
    target_props=[{"name": "pchembl_value_Mean", "task": "SINGLECLASS", "th": [6.5]}],
    random_state=42
)

In [2]:
display(dataset.df)

,SMILES,pchembl_value_Mean,Year,QSPRID,pchembl_value_Mean_original
QSPRID,,,,,
MonitoringTutorialDataset_0000,Cc1nn(-c2cc(NC(=O)CCN(C)C)nc(-c3ccc(C)o3)n2)c(...,True,2008.0,MonitoringTutorialDataset_0000,8.68
MonitoringTutorialDataset_0001,Nc1c(C(=O)Nc2ccc([N+](=O)[O-])cc2)sc2c1cc1CCCC...,False,2010.0,MonitoringTutorialDataset_0001,4.82
MonitoringTutorialDataset_0002,O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1,False,2009.0,MonitoringTutorialDataset_0002,5.65
MonitoringTutorialDataset_0003,CNC(=O)C12CC1C(n1cnc3c1nc(C#CCCCCC(=O)OC)nc3NC...,False,2009.0,MonitoringTutorialDataset_0003,5.45
MonitoringTutorialDataset_0004,CCCn1c(=O)c2c(nc3cc(OC)ccn32)n(CCCNC(=O)c2ccc(...,False,2019.0,MonitoringTutorialDataset_0004,5.20
...,...,...,...,...,...
MonitoringTutorialDataset_4077,CNc1ncc(C(=O)NCc2ccc(OC)cc2)c2nc(-c3ccco3)nn12,True,2018.0,MonitoringTutorialDataset_4077,7.09
MonitoringTutorialDataset_4078,Nc1nc(-c2ccco2)c2ncn(C(=O)NCCc3ccccc3)c2n1,True,2008.0,MonitoringTutorialDataset_4078,8.22
MonitoringTutorialDataset_4079,Nc1nc(Nc2ccc(F)cc2)nc(CSc2nnc(N)s2)n1,False,2010.0,MonitoringTutorialDataset_4079,4.89
MonitoringTutorialDataset_4080,CCCOc1ccc(C=Cc2cc3c(c(=O)n(C)c(=O)n3C)n2C)cc1,True,2013.0,MonitoringTutorialDataset_4080,6.51
MonitoringTutorialDataset_4081,CCOC(=O)c1cnc(NCC(C)C)n2nc(-c3ccco3)nc12,True,2014.0,MonitoringTutorialDataset_4081,7.35

In [3]:
# calculate compound features and split dataset into train and test
dataset.prepareDataset(
    split=RandomSplit(test_fraction=0.2, dataset=dataset),
    feature_calculators=[MorganFP(radius=3, nBits=2048)],
    recalculate_features=True,
)

dataset.getDF().head()

,SMILES,pchembl_value_Mean,Year,QSPRID,pchembl_value_Mean_original
QSPRID,,,,,
MonitoringTutorialDataset_0000,Cc1cc(C)n(-c2cc(NC(=O)CCN(C)C)nc(-c3ccc(C)o3)n...,True,2008.0,MonitoringTutorialDataset_0000,8.68
MonitoringTutorialDataset_0001,Nc1c(C(=O)Nc2ccc([N+](=O)[O-])cc2)sc2nc3c(cc12...,False,2010.0,MonitoringTutorialDataset_0001,4.82
MonitoringTutorialDataset_0002,O=C(Nc1nc2ncccc2n2c(=O)n(-c3ccccc3)nc12)c1ccccc1,False,2009.0,MonitoringTutorialDataset_0002,5.65
MonitoringTutorialDataset_0003,CNC(=O)C12CC1C(n1cnc3c(NCc4cccc(Cl)c4)nc(C#CCC...,False,2009.0,MonitoringTutorialDataset_0003,5.45
MonitoringTutorialDataset_0004,CCCn1c(=O)c2c(nc3cc(OC)ccn32)n(CCCNC(=O)c2ccc(...,False,2019.0,MonitoringTutorialDataset_0004,5.20

In [4]:
display(dataset.X)

,MorganFP_MorganFP_0,MorganFP_MorganFP_1,MorganFP_MorganFP_2,MorganFP_MorganFP_3,MorganFP_MorganFP_4,MorganFP_MorganFP_5,MorganFP_MorganFP_6,MorganFP_MorganFP_7,MorganFP_MorganFP_8,MorganFP_MorganFP_9,...,MorganFP_MorganFP_2038,MorganFP_MorganFP_2039,MorganFP_MorganFP_2040,MorganFP_MorganFP_2041,MorganFP_MorganFP_2042,MorganFP_MorganFP_2043,MorganFP_MorganFP_2044,MorganFP_MorganFP_2045,MorganFP_MorganFP_2046,MorganFP_MorganFP_2047
QSPRID,,,,,,,,,,,,,,,,,,,,,
MonitoringTutorialDataset_0221,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
MonitoringTutorialDataset_3644,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_2459,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1315,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1017,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MonitoringTutorialDataset_1130,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
MonitoringTutorialDataset_1294,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
MonitoringTutorialDataset_0860,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
MonitoringTutorialDataset_3507,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_3174,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
display(dataset.X)

,MorganFP_MorganFP_0,MorganFP_MorganFP_1,MorganFP_MorganFP_2,MorganFP_MorganFP_3,MorganFP_MorganFP_4,MorganFP_MorganFP_5,MorganFP_MorganFP_6,MorganFP_MorganFP_7,MorganFP_MorganFP_8,MorganFP_MorganFP_9,...,MorganFP_MorganFP_2038,MorganFP_MorganFP_2039,MorganFP_MorganFP_2040,MorganFP_MorganFP_2041,MorganFP_MorganFP_2042,MorganFP_MorganFP_2043,MorganFP_MorganFP_2044,MorganFP_MorganFP_2045,MorganFP_MorganFP_2046,MorganFP_MorganFP_2047
QSPRID,,,,,,,,,,,,,,,,,,,,,
MonitoringTutorialDataset_0221,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
MonitoringTutorialDataset_3644,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_2459,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1315,False,False,True,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_1017,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MonitoringTutorialDataset_1130,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
MonitoringTutorialDataset_1294,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
MonitoringTutorialDataset_0860,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
MonitoringTutorialDataset_3507,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
MonitoringTutorialDataset_3174,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [31]:
from torch.nn import functional as F
model_sts = STFullyConnected(
    n_dim=dataset.X.shape[1],  # počet vstupních neuronů (počet deskriptorů)
    n_class=1,  # regresní úloha (1 výstup)
    gpus=[],
    device="cpu",
    batch_size=256,
    patience=100,
    tol=1e-4,
    neuron_layers=[4000, 3000, 1000, 200], #[3000, 1500, 500, 100]
    act_fun=F.selu,
    is_reg=False
)
model_sts.fit(dataset.X, dataset.y)

(STFullyConnected(
   (layers): ModuleList(
     (0): Linear(in_features=2048, out_features=4000, bias=True)
     (1): Linear(in_features=4000, out_features=3000, bias=True)
     (2): Linear(in_features=3000, out_features=1000, bias=True)
     (3): Linear(in_features=1000, out_features=200, bias=True)
     (4): Linear(in_features=200, out_features=1, bias=True)
   )
   (dropout): Dropout(p=0.25, inplace=False)
   (criterion): BCELoss()
   (final_layer_activation): Sigmoid()
 ),
 0)

In [32]:
from sklearn.metrics import f1_score

# print(model_sts.predict(dataset.X_ind))
res = model_sts.predict(dataset.X_ind)
res = res > 0.5
print(f1_score(dataset.y_ind, res))

0.8503336510962822

In [11]:
import torch

torch.save(model_sts.state_dict(), 'tutorial_output_test/models/model.pth')

In [33]:
# Create model
from qsprpred.extra.gpu.models.dnn import DNNModel

os.makedirs("tutorial_output_test/models", exist_ok=True)
model = DNNModel(
    base_dir='tutorial_output_test/models',
    name='MonitoringTutorialModel',
    parameters=model_sts.get_params(),
    patience=3,
    tol=0.01,

)

model.initFromDataset(dataset)
print(model.parameters)
model.estimator = model_sts
display(type(model.estimator))
display(model.estimator)

lol
lol
lol
{'act_fun': <function selu at 0x173ed9b20>, 'batch_size': 256, 'device': device(type='cpu'), 'dropout_frac': 0.25, 'gpus': [], 'is_reg': False, 'lr': 1e-05, 'n_class': 1, 'n_dim': 2048, 'n_epochs': 100, 'neuron_layers': [4000, 3000, 1000, 200], 'patience': 100, 'random_seed': 42, 'tol': 0.0001, 'weight_decay': 0}

qsprpred.extra.gpu.models.neural_network.STFullyConnected

STFullyConnected(
  (layers): ModuleList(
    (0): Linear(in_features=2048, out_features=4000, bias=True)
    (1): Linear(in_features=4000, out_features=3000, bias=True)
    (2): Linear(in_features=3000, out_features=1000, bias=True)
    (3): Linear(in_features=1000, out_features=200, bias=True)
    (4): Linear(in_features=200, out_features=1, bias=True)
  )
  (dropout): Dropout(p=0.25, inplace=False)
  (criterion): BCELoss()
  (final_layer_activation): Sigmoid()
)

In [36]:
from sklearn.metrics import accuracy_score
display(accuracy_score(dataset.y_ind, res))

0.8078335373317014

In [34]:
from qsprpred.models import CrossValAssessor, TestSetAssessor

CrossValAssessor("f1")(model, dataset)

KeyboardInterrupt:

array([0.76325758, 0.75737393, 0.77255639, 0.76091082, 0.74664107])

In [35]:
TestSetAssessor("f1")(model, dataset)

KeyboardInterrupt:

In [35]:
display(model.estimator.get_params())

AttributeError: 'str' object has no attribute 'get_params'

In [28]:
model.loadEstimatorFromFile(model_sts )

UnpicklingError: pickle data was truncated

In [42]:
display(model.nClass)
display(type(model.estimator))
display(model.estimator)

2

str

'Uninitialized model.'

In [14]:
CrossValAssessor("f1")(model, dataset)

array([0.76325758, 0.75737393, 0.77255639, 0.76091082, 0.74664107])

In [15]:
TestSetAssessor("f1")(model, dataset)

array([0.76021588])

In [44]:
model.fit(dataset.X, dataset.y, estimator=model_sts)

STFullyConnected(
  (layers): ModuleList(
    (0): Linear(in_features=2048, out_features=200, bias=True)
    (1): Linear(in_features=200, out_features=100, bias=True)
    (2): Linear(in_features=100, out_features=1, bias=True)
  )
  (dropout): Dropout(p=0.25, inplace=False)
  (fc0): Linear(in_features=2048, out_features=256, bias=True)
  (fc1): Linear(in_features=256, out_features=128, bias=True)
  (fc3): Linear(in_features=128, out_features=1, bias=True)
  (criterion): BCELoss()
  (final_layer_activation): Sigmoid()
)